### ISSUE TITLE
Typing Effect on the heading "We are Programmers"

### ISSUE THREAD

**Issue by sakshigoel19** [Algo-Phantoms/Algo-Phantoms-Frontend#101]
I am a GSSOC'21 participant. I would like to emphasize the the heading "We are programmers" by adding a typing effect on the word programmers using javascript.It would enhance the look and feel of the header section.Please assign me this issue.

**Comment by sakshigoel19** [comment]
@Shruti3004 Please assign this issue to me.

**Comment by RahulBansal0502** [comment]
@harikesh409 @ravikr126 I want to work on this issue. Please assign it to me.

**Comment by ravikr126** [comment]
any progress @sakshigoel19 
if you are not do this then i will assign to @RahulBansal0502

**Comment by sakshigoel19** [comment]
@ravikr126 I am having my college exams. I will solve this issue by tomorrow. Please do not unassign me. I am really sorry for the delay.

**Comment by ravikr126** [comment]
Ok no problem .If any issue you faced then msg in comment section or discord server

**Comment by sakshigoel19** [comment]
https://user-images.githubusercontent.com/61665348/112842160-e67bef80-90be-11eb-87d9-31117d275714.mp4

Can you please review it that is it looking fine or some changes are needed? @ravikr126

**Comment by ravikr126** [comment]
Looking great .Can you make little bit more smooth typing effect.if you can .@sakshigoel19

**Comment by sakshigoel19** [comment]
Okay I will try
