### ISSUE TITLE
[Navbar] Transparent Navbar to Solid On scrolling

### ISSUE THREAD

**Issue by archanagandhi** [Algo-Phantoms/Algo-Phantoms-Frontend#102]
Hey @Shruti3004, I've gone through the site. I would like to **change the navbar**. On the landing page, the navbar should be transparent. On scrolling, the navbar will change to solid colour along with the text. 
Right now I found that this navbar is transparent and on scrolling, everything behind the navbar is visible that seem bad.

**Comment by rk05-lenavo** [comment]
I'm the Participant in GSSOC'21. Please assign me this issue under GSSOC'21. I would love to work on this.

**Comment by Shruti3004** [comment]
@archanagandhi go ahead

**Comment by archanagandhi** [comment]
Thanks for Assigning this to me.
