### ISSUE TITLE
Insert a new section containing list of Programing Language

### ISSUE THREAD

**Issue by neha-baisane** [Algo-Phantoms/Algo-Phantoms-Frontend#104]
I would like to introduce a section named "Sharpen you skills" below About us section, which will include a list of different programming languages for user to make easy choice for practise.

As a GSSOC'21 participant I would like to work on this issue .Please assign me this task.

A brief idea is given in picture.
![Capture](https://user-images.githubusercontent.com/64725427/110737255-0acc7500-8253-11eb-9438-11ac4eb7a198.PNG)

**Comment by mdshahansha** [comment]
for each of the language 
we use differnrent icon 
so it will easy to understanf  and familiar with user
allow me to make the changes

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by mdshahansha** [comment]
Hey, I'm also gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me
