### ISSUE TITLE
Hover effect in navbar

### ISSUE THREAD

**Issue by shrishti-c** [Algo-Phantoms/Algo-Phantoms-Frontend#107]
Since the colour are dark themed, hover effect can make it more visible whenever we head to any sub-section. Would love to work on it. :)

**Comment by Ankkkitt** [comment]
Hello, I am a GSSoc'21 Participant and would like to work on this issue. When we hover on nav links, we can increase the font size and also give it some border to look more attractive and highlighted. If you assigned this issue to make it would be great.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by Fpj-11** [comment]
I am a gssoc'21 participant. I would like to work on this issue.

**Comment by ravikr126** [comment]
since this issue is already raised .see issue #102 so I close this issue and participants are requested to raise issues on a specific type not duplicate.if the issue already raises then you can comment on that issue with your innovative ideas that helps you to get assign.
