### ISSUE TITLE
[GSSOC'21] Learn more about Data Structures Section

### ISSUE THREAD

**Issue by malavikarajeshvikraman** [Algo-Phantoms/Algo-Phantoms-Frontend#109]
Hi ! I am Malavika  , participating in  GSSOC'21 .
I would like to add a learn more about  Data structures section, where I would put the various data structures as cards with a learn more button . 
So Kindly please assign me this task.
Something like this .
![Screenshot 2021-03-11 134405](https://user-images.githubusercontent.com/42905287/110756199-e59a2f80-826f-11eb-8d96-7b2404c3ee2e.jpg)

**Comment by malavikarajeshvikraman** [comment]
@Shruti3004 Kindly do assign this task to me

**Comment by ravikr126** [comment]
sure you can work on it @malavikarajeshvikraman

**Comment by Anagha-2000** [comment]
Hi, I'm a participant at GSSOC'2021. Can you please assign me this issue?
