### ISSUE TITLE
Alignment of banner

### ISSUE THREAD

**Issue by iamvaishnav** [Algo-Phantoms/Algo-Phantoms-Frontend#112]
The text in the banner is not center aligned. It would look great if it is aligned centrally.
Could you assign this to me?

**Comment by ritesh1731** [comment]
I would like to contribute to this issue under GSSOC21. Can you please assign it to me?

**Comment by ravikr126** [comment]
you can work on it @iamvaishnav

**Comment by Ankita297** [comment]
Can i work on this @ravikr126 @harikesh409 ?

**Comment by harikesh409** [comment]
> Can i work on this @ravikr126 @harikesh409 ?

Yes you can work on it. There is already a PR #141 if needed you can refer to that.

**Comment by ravikr126** [comment]
any progress @Ankita297 ?
