### ISSUE TITLE
Extra whitespace in the github link

### ISSUE THREAD

**Issue by SiddhantChadha** [Algo-Phantoms/Algo-Phantoms-Frontend#113]
Hi!
I was going through the project files and found a bug in the UI. There is an unwanted space after the github link and is quite unpleasant. I am a participant of GSSOC'21, I would like to contribute to this issue.
![2021-03-11 (2)](https://user-images.githubusercontent.com/63542625/110765841-96a5c780-827a-11eb-9576-72dc6fdbadda.png)
Please assign it to me. Looking forward to contribute more in the project.
Thanks

**Comment by harikesh409** [comment]
Issue resolved in #163 .
