### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by Krishan-2000** [Algo-Phantoms/Algo-Phantoms-Frontend#115]
In this it is a procedure to check if an email address is deliverable and valid. It catches typos and It also confirms if a particular email address exists with a reliable domain such as Gmail or Yahoo.

@Shruti3004  Please assign this issue to me.

**Comment by tanwi1234** [comment]
In this we can send verifying message to user by adding link option to check email address exist or not using  php or can use javascript for email validation also.
I am participant of GSSOC'21 .Please assign this issue to me.I would like to work on this project.

**Comment by Krishan-2000** [comment]
To check email address is deliverable and  it's domain is valid using javascript.

**Comment by ravikr126** [comment]
you can start now @Krishan-2000

**Comment by Krishan-2000** [comment]
@ravikr126  I have raised the pr #195 can you please review it. I have raised the pr 6 days ago.
