### ISSUE TITLE
Adding Code editor 

### ISSUE THREAD

**Issue by Deepak-dex** [Algo-Phantoms/Algo-Phantoms-Frontend#117]
## Hey I was  thing of adding two code editors in algo phantom

- Ace editor for all Languages
- Pencode like editor for running html ,css and js in realtime.
 
I have already made pencode clone and know basic about embedding ace editor so you can assign me for this issue

_#gssoc_

**Comment by ravikr126** [comment]
SURE YOU CAN START @Deepak-dex

**Comment by abhinav5481** [comment]
Hi,
I would like to work on it. If it is still open, could you please assign it to me?
