### ISSUE TITLE
# Background Video too large

### ISSUE THREAD

**Issue by Deepak-dex** [Algo-Phantoms/Algo-Phantoms-Frontend#118]
#### Background image is very large (42mb) it affects the performance and not that good looking in small device

We can replace it with animated background made using js library like particle.js or other backgrounds made with vanilla js and css 
which will be much lighter and responsive.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by ravikr126** [comment]
can you implement and send ss here? @Deepak-dex
