### ISSUE TITLE
Alignment Problem of Banner Text

### ISSUE THREAD

**Issue by dsnehasish74** [Algo-Phantoms/Algo-Phantoms-Frontend#12]
![Screenshot (518)](https://user-images.githubusercontent.com/58779604/106750356-c21b0e00-664d-11eb-9ee0-d850d8764a46.png)
The Text is not centered properly and also some text like "we are" is not visible. I would love to fix this issue. Please assign this to me. And If you have any work can you can mention I want to contribute to this repo.

**Comment by DeepanshuSarswat** [comment]
I would like to solve this problem as a part of girl Script Summer of code 2021

**Comment by ChitvanRamani22** [comment]
@dsnehasish74 i would like to work on this issue could you please assign this to me.

**Comment by medhavi11** [comment]
I would like to work on this issue, I am GSSOC 2021 participant.

**Comment by ShrutiKhatri826** [comment]
I am a GSSOC'21 participant. I would love to take on this issue. Can you please assign it to me? Hope to hear from you soon!

**Comment by ravikr126** [comment]
hii @dsnehasish74 this issue is already solved so I close this issue .you can work on other issues also
