### ISSUE TITLE
background animation to be replaced with a gif and changing of the unorganized footer

### ISSUE THREAD

**Issue by oneknucklehead** [Algo-Phantoms/Algo-Phantoms-Frontend#120]
replacing the background video of the website with a gif would make the website run much faster and also the footer seems a bit unorganized
Can I please get assigned to this issue?

**Comment by dibyanshu-mohanty** [comment]
The Background video is too large and it affects the rendering of the page, this can be replaced with a gif which would make it faster and the footer needs some extra links for Linkedin and Instagram. 
@Shruti3004 Can i work on this issue?

**Comment by Shruti3004** [comment]
@dibyanshu-mohanty footer issue have already been created and people are working on it, you can replace the background video with a gif.

**Comment by Shruti3004** [comment]
@oneknucklehead and @dibyanshu-mohanty can you guys collectively work on this issue.

**Comment by oneknucklehead** [comment]
@Shruti3004 Yeah sure if @dibyanshu-mohanty is okay with working on the issue together. :3

**Comment by dibyanshu-mohanty** [comment]
@Shruti3004 . Thanks , @oneknucklehead I am okay with it. :)

**Comment by oneknucklehead** [comment]
@Shruti3004 Would we be assigned to this issue?
