### ISSUE TITLE
Contact us bar is too large

### ISSUE THREAD

**Issue by oneknucklehead** [Algo-Phantoms/Algo-Phantoms-Frontend#121]
The styling of the contact us bar seems too large. changing it to a decent size would be okay.
Can I get assigned to this issue?

**Comment by maanpatel2492** [comment]
Hey,I can work on this issue.
(under GSSOC'21).

**Comment by Fpj-11** [comment]
I would like to work on this issue.

**Comment by Srijan205** [comment]
i would like to work on this issue

**Comment by muskaan-ag09** [comment]
I would like to work on this. Please assign it to me.

**Comment by ravikr126** [comment]
Sure @oneknucklehead start your work

**Comment by oneknucklehead** [comment]
@ravikr126 assign this issue to me :3
