### ISSUE TITLE
FOOTER RESPONSIVE ISSUE IN MOBILE VERSION

### ISSUE THREAD

**Issue by pushpakumari5117** [Algo-Phantoms/Algo-Phantoms-Frontend#124]
@todi-2000 @diyajaiswal11 @Shruti3004 @rudrakshi99 PLEASE LOOK INTO THE ISSUE, AND ALLOW ME TO CONTRIBUTE TO YOUR PROJECT.
.
.
![contact](https://user-images.githubusercontent.com/68471073/110907071-da5c0800-8332-11eb-903f-6bf1b4dd36c3.png)

** **CONTACT US BUTTON IN FOOTER** **
**ISSUE 1:** 
I want to make changes to the placeholder "ENTER YOUR EMAIL" in the MOBILE VERSION.
**DESCRIPTION:** 
In MOBILE VERSION the placeholder "ENTER YOUR EMAIL" is not fully visible, i.e "ENTER YOUR EMAIL" looks like "ENTER YOUR EM". 
1. To increase the length of the placeholder, So that "ENTER YOUR EMAIL" is fully visible.
2. Also adjust the Contact Us button, i.e padding and margin.

 ![footer](https://user-images.githubusercontent.com/68471073/110905669-d929db80-8330-11eb-9b56-6b8f1220a8ed.png)

**ISSUE 2:**
** **FOOTER-CONTENT** **
**DESCRIPTION:**
All the Contents of the footer are left-aligned, which is not so impressive in MOBILE VERSION.  
I want to make it responsive to the MOBILE VERSION, by aligning content to the CENTER, So that it looks good in MOBILE VERSION.

THANK YOU!!

**Comment by Devenkapoor7303** [comment]
Can I work on this issue under GSSOC 2021

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by pushpakumari5117** [comment]
I have just raised the issue... Project maintainers will assign the
project.... Not me.

**Comment by Dimple115** [comment]
Yup I do no that :)

**Comment by BALASAI1236** [comment]
I am a GSSOC'21 participant, I want to work on this issue, please assign it to me.

**Comment by harikesh409** [comment]
There are already many issues related to the footer responsiveness. #95 #65
