### ISSUE TITLE
Update TEch stack used with their logos 

### ISSUE THREAD

**Issue by rohank2502** [Algo-Phantoms/Algo-Phantoms-Frontend#125]
I will like to  update the tech stack used with their logo this will make our read me file more attractive !! Will start to work as soon as I get assigned !!

**Comment by Abhishek765** [comment]
Let me handle This @rohank2502 can you recheck whether these are the only tech. stack used in this project:

![image](https://user-images.githubusercontent.com/43133456/110980207-9d702f80-838b-11eb-83a7-9725970a48d0.png)

**Comment by ravikr126** [comment]
no need to change readme file @rohank2502
