### ISSUE TITLE
Page for Quizzes

### ISSUE THREAD

**Issue by rray14** [Algo-Phantoms/Algo-Phantoms-Frontend#128]
Hi my name is Ardra Mohan, a participant of GSSoC'21
Currently, the quiz link redirects you to another page, to make the site more feasible I'll create a page for quiz that'll have various sections with different quiz topics
A page for choosing an interested topic for the quiz from the listed ones.
Please assign me this issue
Thanks!

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by ravikr126** [comment]
o

> Hi my name is Ardra Mohan, a participant of GSSoC'21
> Currently, the quiz link redirects you to another page, to make the site more feasible I'll create a page for quiz that'll have various sections with different quiz topics
> A page for choosing an interested topic for the quiz from the listed ones.
> Please assign me this issue
> Thanks!

you can work now @rray14
