### ISSUE TITLE
"Back to top" button should not be displayed when we are already at top.

### ISSUE THREAD

**Issue by frappelatte28** [Algo-Phantoms/Algo-Phantoms-Frontend#13]
![Algo_phantoms](https://user-images.githubusercontent.com/64382399/106865622-71f58780-66f1-11eb-9211-7e34eb16e4cb.png)

**Comment by frappelatte28** [comment]
I would like to work on this issue @diyajaiswal11 @todi-2000

**Comment by archana-9430** [comment]
Please allow me to work on this issue @diyajaiswal11 @todi-2000

**Comment by Shruti3004** [comment]
Yours @frappellate28

**Comment by frappelatte28** [comment]
Hey @Shruti3004  I am not working on this project anymore, I guess you can assign @archana-9430 :)

**Comment by Shruti3004** [comment]
@archana-9430

**Comment by archana-9430** [comment]
> @archana-9430

Yes, I'm here. I'll work on this.

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by shitesh2607** [comment]
I want to work on this issue as participant of gssoc21.

**Comment by shitesh2607** [comment]
@Shruti3004 pls review my pull request. so that I can close this issue.

**Comment by frappelatte28** [comment]
Hey, @shitesh2607 I am not a mentor here! I only reported the issue. You should tag @Shruti3004, I guess she can help. But yeah I saw your commit and I think it should work fine.

**Comment by shitesh2607** [comment]
Thanks @frappelatte28.
