### ISSUE TITLE
WRONG SPELLING USED IN CONDUCT FILE

### ISSUE THREAD

**Issue by ayush461** [Algo-Phantoms/Algo-Phantoms-Frontend#133]
@rudrakshi99 @todi-2000  @Shruti3004 
I am participant of GSSOC21.
please allow me to correct the spellings of BEHAVIOUR, in conduct.md  file

**Comment by ayush461** [comment]
Total 6 spelling mistakes are there.

**Comment by Fpj-11** [comment]
I am a gssoc'21 participant. I would like to work on this issue.

**Comment by Diksha-11** [comment]
I am a GSSOC'21 participant. I would like to work on this issue of correcting the spellings.
@rudrakshi99 @todi-2000 @Shruti3004

**Comment by Shruti3004** [comment]
@ayush461 go ahead

**Comment by ayush461** [comment]
@Shruti3004 done, please review my PR.
