### ISSUE TITLE
Adding pointer as a cursor to contact us and do some enhancements

### ISSUE THREAD

**Issue by Sweeti-Gupta** [Algo-Phantoms/Algo-Phantoms-Frontend#139]
I want to do some changes in this project that will give  it a better look:
1) I want to add pointer as a cursor and some other hover properties to "contact us"
2) I want to horizontolly align the paragraphs in header in center as it is not looking in the center.
3) I want to add proper margins to the anchor tags in "useful links" and "features" to gibe both a similar look.

Hey @todi-2000 , I want to contribute to this as a part of GSSOC'21. Please assign this to me.

**Comment by ravikr126** [comment]
already raised issue please check previous issues
