### ISSUE TITLE
Documentation - Spelling error and spacing error

### ISSUE THREAD

**Issue by frappelatte28** [Algo-Phantoms/Algo-Phantoms-Frontend#14]
![Algo_phantom_docError](https://user-images.githubusercontent.com/64382399/106870639-57bea800-66f7-11eb-9136-945958f009d2.jpeg)

**Comment by frappelatte28** [comment]
@diyajaiswal11 @todi-2000 @dheerajkotwani Can i raise a PR?

**Comment by gaurav24072002** [comment]
I would like to contribute in this issue please assign it to me.

**Comment by ChitvanRamani22** [comment]
I would like to contribute, can you please assign this to me.

**Comment by IdealisticINTJ** [comment]
I would like to work on this. Please assign this to me.

**Comment by Shruti3004** [comment]
Go ahead @gaurav24072002
