### ISSUE TITLE
Footer section is not organized.

### ISSUE THREAD

**Issue by Pranjal-Yadav17** [Algo-Phantoms/Algo-Phantoms-Frontend#143]
The footer section is not organized/ aligned properly. I would like to work on this issue
![issue created](https://user-images.githubusercontent.com/73348609/111063914-38295500-84d7-11eb-9760-6a4b193babb4.JPG)

**Comment by AbhishekSharma-86** [comment]
Hello @Pranjal-Yadav17 ,
I am a participant of GSSoC, and i would like to work on this issue.
please assign me this issue

**Comment by RahulBansal0502** [comment]
@harikesh409 @ravikr126 I also want to work on this issue. Please assign it to me.

**Comment by ravikr126** [comment]
this is duplicate issue
