### ISSUE TITLE
When navigate to team section, About section is missing from navbar.

### ISSUE THREAD

**Issue by aashi2912** [Algo-Phantoms/Algo-Phantoms-Frontend#145]
I would like to fix this issue. Whenever we click on team and goes to team.html page about section from navbar is missing. It's kind of bug or not proper structure management of website.

I am from GSSOC'21. 
@todi-2000 @diyajaiswal11 @Shruti3004 @rudrakshi99 
 assign this issue to me :)

**Comment by ravikr126** [comment]
hii @aashi2912 someone already raised this issue on the navbar.I think you need to check previous issues first while raised issues.
