### ISSUE TITLE
Add Quiz section in navbar.

### ISSUE THREAD

**Issue by aashi2912** [Algo-Phantoms/Algo-Phantoms-Frontend#146]
In Documentation of this project it is written that Quiz section should be there for DSA.
I would like to initiate and try to build this section by starting with adding section in navbar.

@todi-2000 @diyajaiswal11 GSSOC participant.
assign this issue to me :)!

**Comment by vivek247703** [comment]
Hii,
I would like to add quiz section in nav bar.
Quiz will be topic wise and also level wise .
Where user can learn and attempt quiz according .Assign This issue To Me :)

**Comment by ravikr126** [comment]
The same issues raised before and I also assign someone to this type of issues
