### ISSUE TITLE
Quiz Contest section

### ISSUE THREAD

**Issue by Anupreetadas** [Algo-Phantoms/Algo-Phantoms-Frontend#149]
Hi,
Hi, I'm a GSSOC'21 participant.
I would like to add a quiz section which would have more detailed questions about the data structure level wise(Easy,medium,hard) .As the quiz will be completed the scores along with the rank in the leaderboard for the person playing the quiz will be displayed.

**Comment by vivek247703** [comment]
Hii,
I would like to add quiz section in nav bar.
Quiz will be topic wise and also level wise .
Where user can learn and attempt quiz according .

**Comment by vivek247703** [comment]
Please assign me this issue

**Comment by ravikr126** [comment]
the issue already raise #128
