### ISSUE TITLE
Updating Github logo 

### ISSUE THREAD

**Issue by Astrodevil** [Algo-Phantoms/Algo-Phantoms-Frontend#151]
I am Amitesh Anand, a GSSoC 2021 participant.
**I want to change Github logo in Follow us Section, Color of the logo is not perfectly matching the background**
*Please assign this task to me.*

**Comment by harikesh409** [comment]
Go ahead @Astrodevil

**Comment by Astrodevil** [comment]
Through PR  #163  I Changed the logo color @harikesh409
