### ISSUE TITLE
Add target="_blank" attribute in handpicked hyperlinks.

### ISSUE THREAD

**Issue by harjasnagi** [Algo-Phantoms/Algo-Phantoms-Frontend#154]
Almost all the hyperlinks open in the same tab and not new tab due to which if a user wishes to come back to the website he will have to lose his activity on the hyperlinked page and hit back button. It would be better if links open in new tab so as to have **_easy access back to the website_**.
I would be grateful if this issue is found worthy and if I'm assigned this task.

**Comment by harikesh409** [comment]
Go ahead @harjasnagi
