### ISSUE TITLE
adding typer animation to "WE are programmers" using js

### ISSUE THREAD

**Issue by bitaashna** [Algo-Phantoms/Algo-Phantoms-Frontend#155]
I want to add following typer section.
 I have attached the gif below to show what i want to do  "Building your social brand"
Can u please assign me this issue under the label **GSSOC'21**
I would like to work on it.
@diyajaiswal11 @Shruti3004 @todi-2000 @rudrakshi99 
![20210315_192206](https://user-images.githubusercontent.com/57864526/111164841-6fc1fb00-85c4-11eb-8a19-6e62787e559b.gif)

**Comment by harikesh409** [comment]
Duplicate of #101
