### ISSUE TITLE
About section is not showing in the navigation bar when we click on team section

### ISSUE THREAD

**Issue by Sweeti-Gupta** [Algo-Phantoms/Algo-Phantoms-Frontend#156]
When we open "team section", the about section vanishes in the navigation bar. I want to improve it show that about section will show there and user could quickly visit to that section from the navigation bar.
Hey @geekquad , I want to solve this issue as a part of GSSOC'21. Please assign me this issue.

![Screenshot (2698)_LI](https://user-images.githubusercontent.com/79096136/111165184-c0395880-85c4-11eb-89b3-8be3ca4d6631.jpg)

**Comment by ravikr126** [comment]
the duplicate issue already raise #74 see it and please raise relevant issues

**Comment by Sweeti-Gupta** [comment]
Hey @ravikr126 , I think these two issues are not same. Issue #74 was about the modification of "About Us" section but I am talking about the bug that the "About" section is not showing in the navigation bar when we are clicking on or visiting "Team" section. Issue #74 has been resolved by the PR #122 but I don't see the improvement which I am talking about.


Please check the image. Here "About" section is not showing but it should be there in the navigation bar.
So, please assign this issue to me as apart of GSSOC'21.

![Screenshot (2701)_LI](https://user-images.githubusercontent.com/79096136/111330897-5d17f680-8696-11eb-9e3a-cc3362dbbed2.jpg)

**Comment by ravikr126** [comment]
hii @Sweeti-Gupta please check the website again https://algo-phantoms.github.io/Algo-Phantoms-Frontend/#about

**Comment by Sweeti-Gupta** [comment]
Ok sir
