### ISSUE TITLE
Adding a 404 page

### ISSUE THREAD

**Issue by surbhi594** [Algo-Phantoms/Algo-Phantoms-Frontend#166]
To add a 404 error page to keep a visitor on your site even if he/she hits a page that doesn't exist. Please assign this issue to me @rudrakshi99 as I'm the participant of GSSOC'21.

**Comment by harikesh409** [comment]
Go ahead @surbhi594

**Comment by Spardha-hash** [comment]
I also want to contribute to this issue....Can I do??

**Comment by bishalshaw-164** [comment]
Hi
I would like to add a 404 page,
Would you please assign me to do this.

**Comment by harikesh409** [comment]
@Spardha-hash and @bishalshaw-164 the issues are being assigned on first come first serve basis, you can contribute to other issues.

**Comment by harikesh409** [comment]
@Surabhi0910 make a single PR not multiple PRs for each file.

**Comment by ravikr126** [comment]
@surbhi594  what about your pr???

**Comment by surbhi594** [comment]
Sir, I have created pr #381.

**Comment by Ankita297** [comment]
Can i work on this @harikesh409 ?

**Comment by harikesh409** [comment]
> Can i work on this @harikesh409 ?

Already it is being worked on by @surbhi594 in #381 if there is no update from her within a day or two I will assign it to you.

**Comment by Ankita297** [comment]
Can i work on this @harikesh409 ?

**Comment by harikesh409** [comment]
> Can i work on this @harikesh409 ?

Yes, you can work on it, check the changes requested in #381. If you have a separate idea or design in mind you can propose it with.
