### ISSUE TITLE
Fixing the about us title 

### ISSUE THREAD

**Issue by gnikita432** [Algo-Phantoms/Algo-Phantoms-Frontend#171]
The about section is not responsive and  
The about us title is coming up on the sidebar in mobile view
![aissue1](https://user-images.githubusercontent.com/61223163/111309153-93974680-8681-11eb-9227-e70b93c4ec09.PNG)

**Comment by gnikita432** [comment]
I am a GSSOC'21 participant can you please assign me this issue under gssoc

**Comment by ravikr126** [comment]
this is a duplicate issue.
