### ISSUE TITLE
Responsive home section

### ISSUE THREAD

**Issue by gnikita432** [Algo-Phantoms/Algo-Phantoms-Frontend#173]
The home section is not responsive. All the text in the home section is aligned to the right side and the font-size is also too large for mobile view. 
![aissue2](https://user-images.githubusercontent.com/61223163/111309516-00124580-8682-11eb-8919-dd65885d9b52.PNG)
I am a GSSOC'21 participant can you please assign me this issue under gssoc.

**Comment by harikesh409** [comment]
Go ahead @gnikita432

**Comment by gnikita432** [comment]
Thank you for assigning.
