### ISSUE TITLE
Two Back to Top Buttons

### ISSUE THREAD

**Issue by deeptea22** [Algo-Phantoms/Algo-Phantoms-Frontend#174]
Upon opening the team page, when we scroll to the bottom, there is the presence of two back to top buttons. Would like to work on this issue. Please assign this to me as a part of GSSoC'21. Thank you :)

Screenshot:
![image](https://user-images.githubusercontent.com/67323371/111309825-55e6ed80-8682-11eb-86e6-86c48485d05b.png)

**Comment by harikesh409** [comment]
Go ahead and work on it @deeptea22

**Comment by deeptea22** [comment]
Thank you :)
