### ISSUE TITLE
Changing the background of About Us

### ISSUE THREAD

**Issue by Spardha-hash** [Algo-Phantoms/Algo-Phantoms-Frontend#175]
Hey @harikesh409 I want to change the background of the about us as when I was scrolling then it seems to me incomplete and this part was looking different from the whole page so please assign this issue to me.

**Comment by RahulBansal0502** [comment]
I also want to work on the same issue.

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue?

**Comment by harikesh409** [comment]
In #122 the about us section is being modified and with this new change the white background is looking fine only.

**Comment by agamjotsingh18** [comment]
would you like to assign this issue to me ? Regards!

**Comment by RahulBansal0502** [comment]
> In #122 the about us section is being modified and with this new change the white background is looking fine only.

@harikesh409 I want to use white but its gradient like in #443 which seems cool

**Comment by harikesh409** [comment]
> > In #122 the about us section is being modified and with this new change the white background is looking fine only.
> 
> @harikesh409 I want to use white but its gradient like in #443 which seems cool

What ever the color no need to change it.
