### ISSUE TITLE
Editing the banner text color and grammatical correction.

### ISSUE THREAD

**Issue by apoorva-s1301** [Algo-Phantoms/Algo-Phantoms-Frontend#176]
Hey, I'm a participant of GSSOC'21. I'd like to work on the following changes.
The flashes of the background banner video clashes with the light colored tone of the words "focusses" and "data" in the banner text. Can I try fixing it ?
Also, I really don't want to sound rude correcting the grammar of the website ,but I feel the word "focusses" should be replaced by "focusing" both in the banner text and the about us section. If you find that the grammatical change is not needed, I'd simply work on the text color.
Looking forward to your response regarding the same.

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue?

**Comment by ravikr126** [comment]
someone already raise this issue before
