### ISSUE TITLE
CREATE A SIGN IN / SIGN UP page and an form section 

### ISSUE THREAD

**Issue by saswatsam786** [Algo-Phantoms/Algo-Phantoms-Frontend#177]
I am GSSOC'21 participant.

 I want to create a sign-in/sign-up section in the project. Which will allow users to log in.
I will also add how do you get to know about us form just above the footer.

Please assign me this.

**Comment by shitesh2607** [comment]
Hi @Shruti3004, Hitesh here I want work on this issue. So, can you plz assign it to me?
it will not take much time to complete.

**Comment by harikesh409** [comment]
Go ahead @saswatsam786

**Comment by harikesh409** [comment]
Any progress @saswatsam786

**Comment by saswatsam786** [comment]
My practicals are going on ....it will be over in a week ... I have completed half of my work .....just give me one or two weeks. I will submit and give my progress in a week or two.

**Comment by Muskan-creator** [comment]
can i work on this issue @harikesh409

**Comment by harikesh409** [comment]
> My practicals are going on ....it will be over in a week ... I have completed half of my work .....just give me one or two weeks. I will submit and give my progress in a week or two.
already 2 weeks are gone and again 2 weeks time is very huge make a PR with your changes and as @Muskan-creator she can continue as you are having exams you can work parallelly whenever possible, are you okay like this?

**Comment by saswatsam786** [comment]
OKK please give me 4-5 days. I will try if not Muskan can continue. I am new to all this ... I have to learn, and that's why it takes time. Please give me 4-5 days then after that  Muskan can carry on.

**Comment by harikesh409** [comment]
> OKK please give me 4-5 days. I will try if not Muskan can continue. I am new to all this ... I have to learn, and that's why it takes time. Please give me 4-5 days then after that Muskan can carry on.

Okay sure.

**Comment by ravikr126** [comment]
any progress @saswatsam786 ??? or i will assign this issue to @Muskan-creator

**Comment by Ankita297** [comment]
Can i work on this @harikesh409 ?

**Comment by harikesh409** [comment]
> Can i work on this @harikesh409 ?

Already PR review is going on, if the requested changes are not done then I will assign it to you.
