### ISSUE TITLE
Link is not Working

### ISSUE THREAD

**Issue by Devenkapoor7303** [Algo-Phantoms/Algo-Phantoms-Frontend#18]
In the Useful Links, the contact link is not working.
![Issue](https://user-images.githubusercontent.com/73438023/107268259-e9b70f80-6a6d-11eb-9779-88048b7df550.PNG)

**Comment by ranjal007** [comment]
Hey @Devenkapoor7303  Can I work on this issue?

**Comment by Devenkapoor7303** [comment]
Go Ahead @ranjal007

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by maanpatel2492** [comment]
I can solve this.
(under GSSOC21).

**Comment by Simran2337** [comment]
i want to contribute as a GSSOC participant

**Comment by ravikr126** [comment]
hii @Devenkapoor7303 which link is not working??

**Comment by harikesh409** [comment]
The contact link is correctly pointed to the footer only.
