### ISSUE TITLE
Add animation.

### ISSUE THREAD

**Issue by VishwaRaj-21** [Algo-Phantoms/Algo-Phantoms-Frontend#182]
I am GSSOC'21 participant.
I would like to add animations.
Please assign this to me

**Comment by harikesh409** [comment]
Can you tell us more like where you want to add the animations and what kind of animations you want to add?

**Comment by simranbhalla3** [comment]
Hii Can i work on this issue? I can add animations like page loading and coming on the screen as we scroll down and many more , i m a gssoc participant @harikesh409

**Comment by ravikr126** [comment]
are you like to work on it or not @VishwaRaj-21 ???????

**Comment by Sonaljain6431** [comment]
Hey @VishwaRaj-21! I am interested to work on this issue. Would you like to assign it to me?

**Comment by harikesh409** [comment]
Closing due to inactive.
