### ISSUE TITLE
About us section

### ISSUE THREAD

**Issue by harshb02** [Algo-Phantoms/Algo-Phantoms-Frontend#188]
I want to make the about us section a little bit more stylish and good looking

**Comment by harikesh409** [comment]
What are you planning to do @harshb02 ?

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant in this project. could you please assign me this?

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by Ankita297** [comment]
we can add svg icon or any image .

**Comment by harikesh409** [comment]
> we can add svg icon or any image .

there is already the algo phantoms logo and social media icons what other icons or image you want to add?

**Comment by pragati-kumar** [comment]
Hello @harikesh409 . I'm a GSSOC'21 participant and I believe that I could help with this issue. We could add a carousel introducing the team behind this idea. A dual theme button could also be introduced for the about us section (dark and light- will use javascript).

**Comment by harshb02** [comment]
> What are you planning to do @harshb02 ?

I want to make the about us section a little more stylish and neat

**Comment by harikesh409** [comment]
> > What are you planning to do @harshb02 ?
> 
> I want to make the about us section a little more stylish and neat

It is looking quite clean and classy as of now. If you want to make it more stylish what kind of styles are you planning to do on it.
