### ISSUE TITLE
Navigating to "Features" section

### ISSUE THREAD

**Issue by preity-p** [Algo-Phantoms/Algo-Phantoms-Frontend#189]
The "Features" section mentioned in the footer includes the code editor, quizzes, DSA guidance and opportunities, but it hasn't been included in the navbar - which is the first section users go to for a site layout.

**Comment by preity-p** [comment]
I could add the Features section to the navbar under the "More" tab, since it's a drop-down with only the roadmap as a child, as a GSSoC'21 participant.

**Comment by harikesh409** [comment]
All the links present under features are third party links so no need to show them in the navbar.
