### ISSUE TITLE
Shifting hamburger menu to the right side of the screen

### ISSUE THREAD

**Issue by hitblunders** [Algo-Phantoms/Algo-Phantoms-Frontend#19]
![image](https://user-images.githubusercontent.com/72441280/107510267-b25d7580-6bc9-11eb-8a24-cace5237c879.png)

The hamburger menu would look better in the right side than below the icon. May I work on this?

**Comment by Nagsenwaghmare** [comment]
@hitblunders should I work on this issue?

**Comment by samfubuki** [comment]
I would like to work on this issue

**Comment by reachaadrika** [comment]
Can I work on this issue?

**Comment by hitblunders** [comment]
> @hitblunders should I work on this issue?

Only project admins can assign the issues.

**Comment by vedant-jain03** [comment]
I have already made a portfolio website of mine and I know the trick behind this.
Please assign me the issue so that I can work further on this. Thankyou
