### ISSUE TITLE
HTML Validation

### ISSUE THREAD

**Issue by tanishq-arya** [Algo-Phantoms/Algo-Phantoms-Frontend#191]
![image](https://user-images.githubusercontent.com/77333275/111481814-53a39280-8759-11eb-9339-9387889fe1b2.png)
The lists are not valid according to html along with some other issues. Please assign me this issue. 
You can check for yourself by uploading the index.html here.
https://validator.w3.org/#validate_by_input

**Comment by kumar-tushar** [comment]
@shruti3004 @harikesh409  Can I work on this and related issues.
I want to resolve all the errors that are shown by Webstorm IDE by Jetbrains.

**Comment by agamjotsingh18** [comment]
Will you like to assign this issue to me ...Regards!

**Comment by harikesh409** [comment]
Go ahead @tanishq-arya

**Comment by tanishq-arya** [comment]
@harikesh409 You can check my PR #239
