### ISSUE TITLE
update READme (how to setup project on system)

### ISSUE THREAD

**Issue by mirakiii** [Algo-Phantoms/Algo-Phantoms-Frontend#193]
## How to setup this project on system?
That's a part every _readme_ should include, and we are missing out on this ! :open_mouth: 
To make this project accessible to every newbie  _open source enthusiast_ out there, our _readme_ should include guideline on how to actually set this up at their end !
If you guys let me contribute on this, do assign this to me under Gssoc'21 :four_leaf_clover: 
Thankyou :)

**Comment by RahulBansal0502** [comment]
I am also want to work on this issue please assign it to me as a GSSOC participant.

**Comment by mirakiii** [comment]
I have completed the work if you guys allow me to send my pr I may send the pr on this issue as soon as you make me assignee :)
Thankyou.

**Comment by harikesh409** [comment]
As mentioned by the project admins we should not update the `README.MD` file.
