### ISSUE TITLE
Enhancement of nav-bar

### ISSUE THREAD

**Issue by Snehakri022** [Algo-Phantoms/Algo-Phantoms-Frontend#194]
I want to work on nav bar enhancement as in more section... i want to add some  file which contain all the important DSA questions to practice as well.
@anubhavitis @malavikarajeshvikraman @harikesh409  assign this issue to me

**Comment by Snehakri022** [comment]
Hi @ravikr126 The Homepage of the website has changed and worsen after merging of the pull request #98 for the issue #49 . So I have just created a page regarding dsapractice where all important questions are there along with the link of the problems. please merge it

**Comment by harikesh409** [comment]
> Hi @ravikr126 The Homepage of the website has changed and worsen after merging of the pull request #98 for the issue #49 . So I have just created a page regarding dsapractice where all important questions are there along with the link of the problems. please merge it

The changes of #98 are reverted kindly pull the new code and check. @Snehakri022

**Comment by ravikr126** [comment]
Hii @Snehakri022 there is some improvement is required to code

**Comment by simranbhalla3** [comment]
HII, can i work on this issue? I can make some changes in the nav bar by adding js and css

**Comment by mdshahansha** [comment]
hey im GGsoc21 participant 
assign this pr to me 
so i can work on it and add some page 
that enhances the user to use more
