### ISSUE TITLE
social-sidebar background color

### ISSUE THREAD

**Issue by lipsa199** [Algo-Phantoms/Algo-Phantoms-Frontend#203]
Description of issue:
** when the webpage minimizes or open in phone size browser the social sidebar is not properly visible on footer part because of the   background color of social sidebar**
![IMG_20210318_123048](https://user-images.githubusercontent.com/76063097/111585850-ef7ae000-87e5-11eb-863d-2c41b5da795d.jpg)

**Comment by lipsa199** [comment]
@Shruti3004  can I work on this issue as a participant of gssoc21?

**Comment by lipsa199** [comment]
@harikesh409 can i work on this as a participant of gssoc21?

**Comment by kumar-tushar** [comment]
@Shruti3004  
I have added an issue regarding the change of FOOTER CONTENT in CENTER (issue #226).
This will solve all problems.
So, I Can I work on this issue as a GSSOC 21 participant?

**Comment by harikesh409** [comment]
The issue is similar to #179 if it is not resolved in that then you can work on it.

**Comment by lipsa199** [comment]
@harikesh409 ok sir

**Comment by kumar-tushar** [comment]
> The issue is similar to #179 if it is not resolved in that then you can work on it.

@harikesh409 The issue is still not resolved for mobile devices.
I want to make the text content of the footer in the center to solve the problem of overlapping.
Can I go ahead?

**Comment by harikesh409** [comment]
> > The issue is similar to #179 if it is not resolved in that then you can work on it.
> 
> @harikesh409 The issue is still not resolved for mobile devices.
> I want to make the text content of the footer in the center to solve the problem of overlapping.
> Can I go ahead?

Already a PR #185 is present for it.

**Comment by harikesh409** [comment]
The social media sidebar has been removed in phone views in #435
