### ISSUE TITLE
Navbar and footer are merging

### ISSUE THREAD

**Issue by satcasm** [Algo-Phantoms/Algo-Phantoms-Frontend#204]
When you click on the the ```contact``` link on the home page. The rendered footer is getting merged with the navbar and it's looking a bit odd.
Would like to improve on it under GSSOC' 21.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/111598175-f0ffd480-87f4-11eb-86de-d78e4cf89c98.png)

**Comment by cmulay** [comment]
Yes ! Even I encountered the same on multiple browsers.

**Comment by satcasm** [comment]
@Shruti3004 can I start working on it?

**Comment by simranbhalla3** [comment]
could you please assign me this issue? I  am a gssoc participant

**Comment by harikesh409** [comment]
@satcasm you can work on it
