### ISSUE TITLE
[GSSOC'21] Some content is hidden behind scroll bar.

### ISSUE THREAD

**Issue by shonali2600** [Algo-Phantoms/Algo-Phantoms-Frontend#207]
## **Describe the bug**

"RoadMap to your DSA" content is not visible  properly on the screen

## **Possible solution**

I'll align it to the correct position.

## **Screenshots**

![algoPhantoms](https://user-images.githubusercontent.com/57946528/111631886-ef94d300-8819-11eb-9fa8-07842ade1575.png)

**Comment by SilverGraph** [comment]
@shonali2600 Looks fine to me

![Screenshot 2021-03-18 184952](https://user-images.githubusercontent.com/74287708/111632519-90838e00-881a-11eb-89d3-a47b4a40f4aa.png)

**Comment by shonali2600** [comment]
Different in different browsers.

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue?

**Comment by harikesh409** [comment]
@shonali2600 can you mention which browser and os you are using to replicate the issue.

**Comment by shonali2600** [comment]
@harikesh409 sir, I am using google chrome in windows10, but while opening on opera browser this issue comes, so I made a change to the file so that it'll work on all the browser.
