### ISSUE TITLE
click issue in Features section 

### ISSUE THREAD

**Issue by Astrodevil** [Algo-Phantoms/Algo-Phantoms-Frontend#208]
## **Describe the bug**

- In the features section the lists are clickable even when cursor is far away.

## **Possible solution**

- May be enhancement in code part by editing bootstrap code/class .
- If anyone wants to solve, go ahead 

https://user-images.githubusercontent.com/73425223/111690560-5b476200-8853-11eb-945c-8e093b9647db.mp4

## **Screenshots**

- Here i attached a short video for this.

**Comment by abhishek96k** [comment]
I would like to work on this issue

**Comment by paaniik** [comment]
I'm a GSSoC participant, and I want to work on this issue please assign to me!

**Comment by paaniik** [comment]
Hey @harikesh409 I'm a GSSoC participant and I want to work in this issue, please assign me this issue.

**Comment by RajatWankhede14** [comment]
Hey @Astrodevil I'm GSSoC participant and I would like to work on this issue. Please assign me this issue.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by preity-p** [comment]
Hi, could I please be assigned this issue as a GSSoC participant?

**Comment by Astrodevil** [comment]
This issue is not yet solved please assign to someone @ravikr126 @harikesh409

**Comment by harikesh409** [comment]
Go ahead @abhishek96k
