### ISSUE TITLE
Broken HTML genereates loads of errors

### ISSUE THREAD

**Issue by dcs-soni** [Algo-Phantoms/Algo-Phantoms-Frontend#211]
Hey. I peeked the website and got to know about the broken code at various places. If there is a plan to refactor those code issues in the website then I can help with this one. Please do consider me to assign under **GSSoC'21**.

Below is the screenshots of some of the issues.

![image](https://user-images.githubusercontent.com/52232900/111749164-6b912880-88b7-11eb-8756-a49e8d3988e4.png)

**Comment by tanishq-arya** [comment]
Repeated issue #191

**Comment by harikesh409** [comment]
Duplicate of #191
