### ISSUE TITLE
Styling the button on DSA.html

### ISSUE THREAD

**Issue by cryptofox17** [Algo-Phantoms/Algo-Phantoms-Frontend#213]
## Is your feature request related to a problem?

No. It's not necessarily problem. The button on DSA.html is too basic and doesn't match the theme of the website. 

## **Describe the solution you'd like**

With just a few css styling it can be stylized without using bootstrap or any other libraries. 

Please assign this issue to me

**Comment by harikesh409** [comment]
GO ahead @cryptofox17. If you can even change the hyperlink to index.html instead of goback script.

**Comment by cryptofox17** [comment]
Thank you for assigning!

**Comment by abstrxtInfinity** [comment]
@harikesh409 I would like to point out that this is a duplicate issue as I have been working on this one and have staged the changes for review as well. pr: #185
issue numbers: #180 #183

**Comment by cryptofox17** [comment]
@abstrxtInfinity I saw the issue but since it didn't have a level tag I thought it wasn't assigned, I apologise for the same. 

@harikesh409 do you think I could just remove the goback script and simply change the hyperlink to index.html page and make some enhancements (if necessary) for this issue?

**Comment by harikesh409** [comment]
@cryptofox17 yes just simply change the hyperlink.

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue?

**Comment by harikesh409** [comment]
@simranbhalla3 Already this issue is being worked by @cryptofox17, you can choose some other issue.
