### ISSUE TITLE
adding navbar in practicedsa.html page

### ISSUE THREAD

**Issue by lipsa199** [Algo-Phantoms/Algo-Phantoms-Frontend#214]
Hey **There is no navbar in practicedsa.html page ,if some one wants to return to home page then he/she have to click the back button so if you want to add the navbar in practicedsa.html then i can help with that one .please consider me as a partcipant of Gssoc21  **
 
![IMG_20210319_221033](https://user-images.githubusercontent.com/76063097/111817367-f1d35c00-8903-11eb-8aff-68e030fbc055.jpg)

**Comment by lipsa199** [comment]
@Shruti3004 can I work on this issue as a participant of gssoc21?

**Comment by harikesh409** [comment]
Go ahead @lipsa199

**Comment by pallavi00021** [comment]
can I work on this issue?? @harikesh409

**Comment by harikesh409** [comment]
@pallavi00021 it is already assigned to @lipsa199, if she is not working then you can work on it.

**Comment by simranbhalla3** [comment]
Could you please assign me with this issue?  I would love to work on it , I am a gssoc participant

**Comment by padmajabhol** [comment]
I want to work on this.

**Comment by harikesh409** [comment]
> I want to work on this.

It is already done and the PR #221 is being reviewed.
