### ISSUE TITLE
Change the colour of scroll bar

### ISSUE THREAD

**Issue by Shruti3004** [Algo-Phantoms/Algo-Phantoms-Frontend#215]

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by Shruti3004** [comment]
go ahead @AshuKV please make the scroll bar of that gradient which looks subtle with our landing page

**Comment by shahbazalam07** [comment]
i also want to work on this issue

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue?
