### ISSUE TITLE
Adding online compiler

### ISSUE THREAD

**Issue by bitaashna** [Algo-Phantoms/Algo-Phantoms-Frontend#218]
## **Is your feature request related to a problem? Please describe.**

- code's link can be shared so we can get advice to make appropriate changes .

## **Describe the solution you'd like**

- online compiler for various languages like Java, C++, Python, etc.
- a simple UI in order to store all your codes written in various languages easily at one place.
- You can share the codes' links that you write with your friends without being worried about them making any changes.
- stores all your code details on your device, which means every code that you write will only be editable on the device where you write your code.

**Comment by bitaashna** [comment]
@Shruti3004 @todi-2000 @rudrakshi99 @diyajaiswal11 Please assign me this issue.
I would like to work on it as a GSSOC'21 participant

**Comment by harikesh409** [comment]
Go ahead @bitaashna

**Comment by bitaashna** [comment]
@harikesh! should i embed separate compiler for each language as I am not able to merge them in one

**Comment by harikesh409** [comment]
> @harikesh! should i embed separate compiler for each language as I am not able to merge them in one

It will not look nice having separate compiler for each language, we need a dropdown with the list of languages. How are you building the compiler?

**Comment by bitaashna** [comment]
I am trying to embed it from different website.

**Comment by bitaashna** [comment]
@harikesh409 Should I build it from scratch?

**Comment by harikesh409** [comment]
> I am trying to embed it from different website.But Only possible to embed compiler for one language at a time.

There are third party APIs you can use, all you need to do is to design the UI part and use AJAX calls to communicate to the site. No need to build the compiler from scratch.

Refs:
https://www.jdoodle.com/compiler-api/
https://www.hackerearth.com/docs/wiki/developers/v3/

**Comment by bitaashna** [comment]
@harikesh409 ok got it!
Thanks:)

**Comment by ravikr126** [comment]
in the footer section there is code editor .you can change with your compiler @bitaashna

**Comment by bitaashna** [comment]
@harikesh409 I don't know why its not working on clicking on compile button .
It's showing an error .Please guide me.
![Screenshot from 2021-03-25 19-44-59](https://user-images.githubusercontent.com/57864526/112487310-a22cde80-8da2-11eb-90f1-3fd5a1e6ad2b.png)
![Screenshot from 2021-03-25 19-27-06](https://user-images.githubusercontent.com/57864526/112487335-a5c06580-8da2-11eb-93f0-c633a1492ede.png)

**Comment by harikesh409** [comment]
> @harikesh409 I don't know why its not working on clicking on compile button .
> It's showing an error .Please guide me.
> ![Screenshot from 2021-03-25 19-44-59](https://user-images.githubusercontent.com/57864526/112487310-a22cde80-8da2-11eb-90f1-3fd5a1e6ad2b.png)
> ![Screenshot from 2021-03-25 19-27-06](https://user-images.githubusercontent.com/57864526/112487335-a5c06580-8da2-11eb-93f0-c633a1492ede.png)

Most of the sites block requests from no origin headers for security reasons. Try running the site on a local server so an origin will be sent to the API and make sure in your ajax calls the `crossDomain` is true.

Ref:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
https://medium.com/@baphemot/understanding-cors-18ad6b478e2b
https://zinoui.com/blog/cross-domain-ajax-request

**Comment by amangupta37** [comment]
I want to work on this issue

**Comment by harikesh409** [comment]
> I want to work on this issue

It is already being worked fi @bitaashna needs help then you can also tag along.

**Comment by harikesh409** [comment]
> I want to work on this issue

Go ahead, already some changes are requested in #274 look into those.

**Comment by ravikr126** [comment]
what is the progress @amangupta37 ?

**Comment by subhangi2731** [comment]
@ravikr126 @harikesh409 please assign this issue to me

**Comment by ravikr126** [comment]
Sure @subhangi2731 you can work on it

**Comment by subhangi2731** [comment]
@harikesh409 @ravikr126 please help me in this 

Access to XMLHttpRequest at 'https://api.hackerearth.com/v4/partner/code-evaluation/submissions/' from origin 'http://127.0.0.1:5500/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I am getting this error by running in live server also please help me

**Comment by harikesh409** [comment]
> @harikesh409 @ravikr126 please help me in this
> 
> Access to XMLHttpRequest at 'https://api.hackerearth.com/v4/partner/code-evaluation/submissions/' from origin 'http://127.0.0.1:5500/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> I am getting this error by running in live server also please help me

Refer the articles present in [this](https://github.com/Algo-Phantoms/Algo-Phantoms-Frontend/issues/218#issuecomment-808691452) comment.
