### ISSUE TITLE
Validating the email in the team page

### ISSUE THREAD

**Issue by 123mansha** [Algo-Phantoms/Algo-Phantoms-Frontend#219]
In the team's contact us page the email field is not validating whether we entered a plaintext or an email i.e., A valid email must contain '@' symbol.
Here, in the below screenshot we can see that no error message is displayed even if we are entering a plain text in the email field.

![algofr](https://user-images.githubusercontent.com/59260493/111881390-3f1ffe00-89d6-11eb-99e6-2c42a2760448.jpg)

I would like to work on this issue.

**Comment by 123mansha** [comment]
@Shruti3004 kindly assign me this issue

**Comment by harikesh409** [comment]
Duplicate of #115
