### ISSUE TITLE
Adding a project ideas section

### ISSUE THREAD

**Issue by gayatri517** [Algo-Phantoms/Algo-Phantoms-Frontend#220]
## Proposal

I want to add a project ideas section in the navbar "more" section. I will provide a link to a website that displays various project ideas for college students.

I want to work on this issue as a participant of GSSOC'21, please assign it to me.

**Comment by RoliGautam** [comment]
hello, I want to contribute in this section . I can add a option in 'more' section. And in that page there will be a list of projects ideas for the students related to different tech slack like  web development, android, machine learning and python , java etc.
Can you assign for this issue as a participant of GSSOC'21.

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant in this project. could you please assign me this?

**Comment by harikesh409** [comment]
That's a nice idea both can work on it.

**Comment by RoliGautam** [comment]
@harikesh409 Sorry due to exams , I was not able to contribute on this issue , Can I still work on it?

**Comment by harikesh409** [comment]
> @harikesh409 Sorry due to exams , I was not able to contribute on this issue , Can I still work on it?

@gayatri517 already added an external link with the list of projects.
