### ISSUE TITLE
Add a suggested Books for DSA webpage under More on nav bar

### ISSUE THREAD

**Issue by sohini3062** [Algo-Phantoms/Algo-Phantoms-Frontend#222]
## **Is your feature request related to a problem? Please describe.**
Along with tons of online material, learners often search for list of books on to get a clearer idea of DSA
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**
A specified page designated for a list of books.
- A clear and concise description of what you want to happen.
Add a link to another webpage which will include list of suggested books and on hovering over each item on the list, we can add a few lines on how that particular book can help. The webpage will require a very simplistic design, just using HTML CSS containing list of books, I have 3 books in mind right now.

**Comment by ravikr126** [comment]
YOU CAN WORK ON IT @sohini3062
