### ISSUE TITLE
"Contact Us" button not working (in footer)

### ISSUE THREAD

**Issue by WaderManasi** [Algo-Phantoms/Algo-Phantoms-Frontend#23]
In footer, email is not being submitted by clicking on "contact us", rather it has not been assigned with button functionality

**Comment by samfubuki** [comment]
I would like to work on this issue as a part of gssoc 21

**Comment by DeepanshuSarswat** [comment]
I would like to solve this problem as a part of girls script summer code 2021

**Comment by ArchishmanSengupta** [comment]
Will the contact us button direct to a mailing link? please clarify

**Comment by Shruti3004** [comment]
Contact us button should link it to the mail **algophantom0101@gmail.com**

**Comment by Shruti3004** [comment]
Go ahead @WaderManasi

**Comment by WaderManasi** [comment]
Yeah sure..Thank you for assigning the task @Shruti3004

**Comment by WaderManasi** [comment]
@Shruti3004  Will you kindly clarify the need of input field =>'Email-id' at left of contact us button?
![mail](https://user-images.githubusercontent.com/52437677/109426977-3d39cf00-7a16-11eb-92de-a90f67c39c63.PNG)

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by Avnish5** [comment]
I am doing web dev from last 1 year.
I am also selected as a participant under GSSOC 2021.
Kindly assign this task to me...

**Comment by raveena69** [comment]
Hi, I'm Raveena and I would like to contribute to this issue.

**Comment by Manish-kasera** [comment]
Hiiii. I Would like to solve this Issue..

**Comment by Goheljay** [comment]
I participated in gssoc 2021.
The "Contact us" Button not work. So I am able to do solve this issue. a have many web designs and also make my portfolio. if see my portfolio you goto my GitHub account I have already mentioned my portfolio link. a small change in code and add some code and the issue will be solved easily. 
So can you assign this issue to me?

**Comment by Pranjal-Yadav17** [comment]
Hey I'm a GSSoc 2021 participant and I would like to solve this issue @Shruti3004 .
![algo phatom](https://user-images.githubusercontent.com/73348609/111023158-6aff1a80-83fd-11eb-9ca9-0f154570e135.JPG)

**Comment by Manish-kasera** [comment]
I had solved the issue and i am going to sent PR request as @WaderManasi is not active from last 23 days @Shruti3004 ..Hope It will acceptable....

**Comment by WaderManasi** [comment]
### @Manish-kasera I have already made PR for this issue 14 days ago..Kindly check it out
![add](https://user-images.githubusercontent.com/52437677/111063109-e67ecb80-84d2-11eb-9a1a-8c7104459fdc.PNG)

**Comment by Manish-kasera** [comment]
Sorry @WaderManasi  i didn't notice.. Extremely Sorry for inconvenience..

**Comment by WaderManasi** [comment]
No issues.

**Comment by ravikr126** [comment]
are you work on it or not @WaderManasi ???

**Comment by WaderManasi** [comment]
Yes I had commited to the branch

**Comment by WaderManasi** [comment]
Kindly let me know if still there is improvement needed.
