### ISSUE TITLE
Query Section or page where users can post their queries

### ISSUE THREAD

**Issue by kumar-tushar** [Algo-Phantoms/Algo-Phantoms-Frontend#230]
There must be some Query Section or a separate webpage for that where users can ask their queries related to DSA and they can get a reply through email

**Comment by abstrxtInfinity** [comment]
I guess we can take a .txt file input of their question

**Comment by RahulBansal0502** [comment]
Yes, I am also thinking the same. I want to revamp the footer. I want to make the contact us section separately where one can fillup of the form for suggestions and for queries or any message he/she wants to convey?

I wanted to make it like the below image. 
![image](https://user-images.githubusercontent.com/56486309/112307753-56593700-8cc7-11eb-805c-fcb15dccb5d0.png)

**Comment by ravikr126** [comment]
this is dublicate issue .same issue is  issue#51
