### ISSUE TITLE
DSA.html does not provide image zoom in feature

### ISSUE THREAD

**Issue by SAHU-01** [Algo-Phantoms/Algo-Phantoms-Frontend#236]
**## **Describe the bug****

On landing at the dsa.html page i.e. the roadmap, its merely a picture , with too many elements , if you intend to keep that image then a zoom into and zoom out of the picture option or feature needs to be added so that its more attractive and legible for users to understand.

**- A clear and concise description of what the bug is.**

the DSA.html page simply contains a big picture but the contents of the picture aren't legible , if the picture is used the zoom in and zoom out feature is missing here, that would atleast help users see seach segment of the roadmap clearly.

## **Possible solution**

**- Describe the solution you thought of.**

I wish to work on this issue as a GSSOC'21 participant  by adding the image zoom in and zoom out feature. This feature will help users to zoom into any particular sector by simly clicking on that part .

**## **Screenshots****

this is what it look now as:

<img width="955" alt="dsa" src="https://user-images.githubusercontent.com/71656941/112251844-fc824e00-8c81-11eb-92c4-3afe6811b456.png">

but if we add the zoom in feature then lets say I click on topics then an additional pop up like this would appear zooming that particular part of the image , somewhat looking like this

<img width="169" alt="top" src="https://user-images.githubusercontent.com/71656941/112251996-44a17080-8c82-11eb-8d45-df9fc83b4052.png">

**- If applicable, add screenshots to help explain your problem.**

there could be another solution to the problem i.e. rather than just adding an image we can use html,css,javascript to actually create a personalized roadmap for Algo-Phantoms specifically.

**Comment by harikesh409** [comment]
![image](https://user-images.githubusercontent.com/3501554/112262505-c51c9d00-8c93-11eb-84cd-d7c5e74c1e9f.png)
On the bottom right there are already + and - buttons to zoom in and zoom out.
