### ISSUE TITLE
Changed the alignment of social buttons

### ISSUE THREAD

**Issue by 123mansha** [Algo-Phantoms/Algo-Phantoms-Frontend#237]
The social buttons were aligned horizontally .

_**Changes done**_

-  Aligned the social buttons vertically.
- Social buttons have appropriate required margins.

_**Before**_

![Screenshot (4)](https://user-images.githubusercontent.com/59260493/112255478-49692300-8c88-11eb-9574-a7b18f6ed1a2.png)

_**After**_

![Screenshot 2021-03-24 095740](https://user-images.githubusercontent.com/59260493/112255484-4bcb7d00-8c88-11eb-96fb-faeef78cdf2a.jpg)

I would like to work on this issue. Please assign me.

**Comment by harikesh409** [comment]
The buttons look much better horizontally why to change them to a vertical layout?

**Comment by 123mansha** [comment]
The **Useful Links** column and the **Features** column were vertically aligned so I thought that aligning the social buttons vertically would look better.
But if it looks better in horizontal alignment, we can keep them horizontally aligned.

**Comment by harikesh409** [comment]
> The **Useful Links** column and the **Features** column were vertically aligned so I thought that aligning the social buttons vertically would look better.
> But if they look better in horizontal alignment, we can keep them horizontally aligned.

In general social icons will be horizontal only no need to change them to vertical alignment.
