### ISSUE TITLE
Links are directing back to homepage

### ISSUE THREAD

**Issue by satcasm** [Algo-Phantoms/Algo-Phantoms-Frontend#242]
The social media icons used in the home page are redirecting back to the homepage as of now.
I think if appropriate end points are not available currently then these icons should be removed from the home page or if they are available I would like to add them.
Would like to work on it under GSSOC' 21.

**Comment by ravikr126** [comment]
don't worry about that link will be added in the future .so you can work on different issues .till now there is no social media page available for algo phantom
