### ISSUE TITLE
Add Disjoint Set Data Structure topic in Complete DSA Guide

### ISSUE THREAD

**Issue by SrishtiSingh2001** [Algo-Phantoms/Algo-Phantoms-Frontend#243]
## Proposal

(A clear and concise description of what the proposal is.)
In Complete RoadMap to DSA, under the section Topics, Disjoint Data Strucrure is not mentioned. It is an important topic and needs to come in the eye of learners so that they can get familiar with it.

I want to work on this issue under GSSOC21. Kindly assign it to me.

**Comment by ravikr126** [comment]
Under roadmap to dsa ,every data structure is mention .you can check it.if you feel you can add some new one then you can work on it
