### ISSUE TITLE
Adding FAQ page 

### ISSUE THREAD

**Issue by Ratnesh4193** [Algo-Phantoms/Algo-Phantoms-Frontend#245]
## **Adding a page containing frequently asked questions **

This will improve the visitors experience.
kindly assign me this issue @harikesh409 .I am a gssoc 2021 participant.

**Comment by arpit456jain** [comment]
@Ratnesh4193  sir I am a Gssoc'21 participant I want to work on this issue. Kindy assign it to me.

**Comment by ravikr126** [comment]
I don't this is much relevant for this website .you can work on a different issue.
