### ISSUE TITLE
Making Image on DSA.html page responsive

### ISSUE THREAD

**Issue by somya51p** [Algo-Phantoms/Algo-Phantoms-Frontend#246]
## **Describe the bug**

The image on the DSA.html page is not responsive.

## **Possible solution**

I wish to make the image responsive so that it fits screens of all sizes.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![1](https://user-images.githubusercontent.com/64978837/112430643-a94ce180-8cfb-11eb-8083-7bdee46d51ec.PNG)

**Comment by ravikr126** [comment]
1st this is not an image.
2nd .it is responsive.
I don't this it needed any enhancement and someone already raises this issue so I closed this issue.please raise relevant issue and don't raise duplicate also
