### ISSUE TITLE
Update README file 

### ISSUE THREAD

**Issue by ANSHIKA1806** [Algo-Phantoms/Algo-Phantoms-Frontend#247]
@todi-2000 @Shruti3004 @ravikr126 @harikesh409 @Adyasha8105 
README is the first file one should read when starting a new project. It's a set of useful information about a project, and a kind of manual. A README text file appears in many various places and refers not only to programming. So i want to make your README file more meaningful and more easier to understand the whole project.

**Comment by ANSHIKA1806** [comment]
@todi-2000 @Shruti3004 @ravikr126 @harikesh409 @Adyasha8105 
please assign this task to me ,I would love to contribute in your organization .
thank you

**Comment by ravikr126** [comment]
You can work now @ANSHIKA1806

**Comment by ANSHIKA1806** [comment]
@ravikr126  thank you so much sir .

**Comment by ravikr126** [comment]
hii @ANSHIKA1806 there is some issue that no one can change readme file .So i can't merge you pull request
