### ISSUE TITLE
Enhancing the Contact Us section

### ISSUE THREAD

**Issue by somya51p** [Algo-Phantoms/Algo-Phantoms-Frontend#248]
## **Is your feature request related to a problem? Please describe.**

-We have a section for email entry only, there should also be a text-area for the users to write messages they wish to send.

## **Describe the solution you'd like**

-Making a text-box for users to write their messages, and also displaying an alert whenever the user clicks the 'Contact Us' button.

I wish to contribute to this issue. Please assign me the same under GSSOC'21.

**Comment by ravikr126** [comment]
already raised issue @somya51p
