### ISSUE TITLE
Sidebar link does not redirect to Github

### ISSUE THREAD

**Issue by aanchal-fatwani** [Algo-Phantoms/Algo-Phantoms-Frontend#249]
ISSUE DETAILS
Currently, the sidebar link for Github does not redirect to the link of the organization's Github.
It should be redirected to a valid Github link similar to the Follow tabs of the footer section.

**Comment by aanchal-fatwani** [comment]
Hey @ravikr126, @harikesh409, I am a GSSOC 2021 participant. I would like to work on the issue. 
Could you please update the issue with relevant tags and assign the same?

**Comment by harikesh409** [comment]
Duplicate of #242
