### ISSUE TITLE
Features are not working

### ISSUE THREAD

**Issue by sheetalj2205** [Algo-Phantoms/Algo-Phantoms-Frontend#25]
In the features section code editor, quizzes ad DSA guidance are not the links and are not working. I would like to work on this issue for GSSOC'21.

**Comment by Shruti3004** [comment]
Yours @sheetalj2205

**Comment by sheetalj2205** [comment]
> Yours @sheetalj2205

Thanks for assigning, can you please tell me to which links do you want to redirect them all?

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by WebVishal** [comment]
hi, can I Contribute to this issue as of part the gssoc'21

**Comment by Simran2337** [comment]
i want to contribute

**Comment by satyampandeygit** [comment]
@Shruti3004 this is resolved I think as all the links are working correctly you may close this issue, if anything is left to be done kindly point out I will try to do that.
