### ISSUE TITLE
MAKE navbar more align 

### ISSUE THREAD

**Issue by ravikr126** [Algo-Phantoms/Algo-Phantoms-Frontend#251]
## **Describe the bug**

- see the 
Home(current)
About
Team
Contact
More 
Are in the center.

## **Possible solution**

- make it on the right side of the navbar

**Comment by RahulBansal0502** [comment]
Assign it to me. I want to work on this issue.

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant in this project. could you please assign me this? i can fix this.

**Comment by Rajashri14** [comment]
I want to work on this issue. Please assign this issue to me.
This regarding GSSOC'21.

**Comment by prayas7102** [comment]
I want to work on this issue. Please assign this issue to me.

**Comment by ravikr126** [comment]
ok @RahulBansal0502 you can start now

**Comment by RahulBansal0502** [comment]
ok
