### ISSUE TITLE
bug in practice dsa sheet 

### ISSUE THREAD

**Issue by Muskan-creator** [Algo-Phantoms/Algo-Phantoms-Frontend#256]
In practice sheet  there is no go back button showing but there is function for that .I want to make styling  go back button for that so that we does not have to close window again and again.Other option is that I can create a new tab for that so that my home page remains in window and I can shift to both.
Please assign this issue to me as a part of gssoc contribution.
Thankyou

**Comment by ravikr126** [comment]
Someone already raise this issue .Please don't raise duplicate issues . @Muskan-creator .You van work on different issues also
