### ISSUE TITLE
Open source contribution feature

### ISSUE THREAD

**Issue by nasir-khan01** [Algo-Phantoms/Algo-Phantoms-Frontend#257]
**Why this feature is required ?**
This feature will help the open source contributors to browse the projects of Algo phantoms directly from features section. This will greatly help  Those students who not only wants to improve their DSA skills but also want to contribute to the project.

HI, I am a GSSOC21 Participant and i have already implemented this feature in my local machine  , Please assign this issue to me so that i can create a PR.
Thank You

**Comment by ravikr126** [comment]
Someone already raised issue on this.
You can work on different issues @nasir-khan01
