### ISSUE TITLE
dropdown menu styling in more section

### ISSUE THREAD

**Issue by Muskan-creator** [Algo-Phantoms/Algo-Phantoms-Frontend#260]
## **Is your feature request related to a problem? Please describe.**

The problem is that current  dropdown menu in more section is very simple and not with matching with website theme .

## **Describe the solution you'd like**

-We can add animations and hover effect in  buttons or text which changes when clicked and also matched with UI of website
![algophantoms](https://user-images.githubusercontent.com/59757988/112636920-a7059700-8e63-11eb-9d49-8ade1bf77b51.png)

**Comment by Muskan-creator** [comment]
I have made changes in my local machine .Please assign it to me so that I can proceed and make a PR .

**Comment by harikesh409** [comment]
@Muskan-creator can you post some screenshots to show what kind of effects you added. The page already became slow so we don't want any kind of unnecessary load which might increate the weight of the page.

**Comment by Muskan-creator** [comment]
https://user-images.githubusercontent.com/59757988/112718479-518bc180-8f19-11eb-80b6-07a651740596.mp4

**Comment by Muskan-creator** [comment]
Can i work on this @harikesh409 ?

**Comment by harikesh409** [comment]
> Can i work on this @harikesh409 ?

Yes go ahead.
