### ISSUE TITLE
DSA Practice Sheet

### ISSUE THREAD

**Issue by tier3guy** [Algo-Phantoms/Algo-Phantoms-Frontend#269]
The practice page only includes Babbar's 450 question and even than that  the UI is not so good . I  made changes on my local machine improved the UI of the page and added more resource to practice DSA .
These are the changes that I made : 

![2021-03-27 (2)](https://user-images.githubusercontent.com/73595465/112723158-3168fc00-8f33-11eb-9593-826e44189675.png)
![2021-03-27 (3)](https://user-images.githubusercontent.com/73595465/112723162-3463ec80-8f33-11eb-940d-ac7dc581aa8d.png)
![2021-03-27 (4)](https://user-images.githubusercontent.com/73595465/112723164-34fc8300-8f33-11eb-878d-7b976d95be26.png)

@harikesh409  Assign me this issue so that I can go ahead with the PR .

**Comment by harikesh409** [comment]
The style is already being changed in #185. If you want you can add the additional questions.

**Comment by ravikr126** [comment]
Someone already work on this issue and also.adding new questions.so.it not possible for any mentors to assigned this issues to you @tier3guy .So you can work on different areas of this project.

**Comment by tier3guy** [comment]
Okay sir
