### ISSUE TITLE
Site is not browser comaptible

### ISSUE THREAD

**Issue by Shruti3004** [Algo-Phantoms/Algo-Phantoms-Frontend#27]
![Screenshot from 2021-02-27 03-34-20](https://user-images.githubusercontent.com/56133783/109360152-b4535400-78ac-11eb-84b5-013a26b3e010.png)
On Firefox the background video is not visible.

**Comment by Ankita297** [comment]
Mam , the  size of video is large so i think it takes  some time to upload . But after  some time it is visible  and after adding the preloader the issue will be resolved .

**Comment by Avnish5** [comment]
I am doing web dev from last 1 year.
I am also selected as a participant under GSSOC 2021.
Kindly assign this task to me...

**Comment by medhavi11** [comment]
I would like to work on this issue, I am GSSOC 2021 participant.

**Comment by Shruti3004** [comment]
Go ahead @Avnish5

**Comment by Avnish5** [comment]
Thanku mam for assigning this task to me.

**Comment by Avnish5** [comment]
@Shruti3004 mam can you please elaborate the issues like in which browsers site is not compatible.

**Comment by Avnish5** [comment]
![Algo Phantoms - Mozilla Firefox 08-03-2021 15_24_49](https://user-images.githubusercontent.com/68527921/110305300-a0cd8900-8022-11eb-8ed0-33b2e4b7699f.png)
 @Shruti3004 There is no need for any change in the code.
The background-video work properly in the fire-fox.
Kindly check it .
