### ISSUE TITLE
 Improving the UI of cards in teams page 

### ISSUE THREAD

**Issue by cryptofox17** [Algo-Phantoms/Algo-Phantoms-Frontend#279]
## Is your feature request related to a problem? 

It is not problem, but the colors that are used for cards (just grey for the text)  in teams page doesn't appear striking as the contrast is too low. Even the icons are of the same color. The font size could also be increased for better readability. 

## **Describe the solution you'd like**

Increasing the font size and using the the primary color of the website for icons and the names of the team members. Also, improve the look of the cards. 
I would like to work on this issue.

**Comment by harshb02** [comment]
I would like to work on this issue

**Comment by harikesh409** [comment]
> I would like to work on this issue

As @cryptofox17 raised the issue he will be given first priority, if he says it is okay for you to work I can assign it.

**Comment by cryptofox17** [comment]
Ok, he can work on this issue as he wishes to @harikesh409

**Comment by harikesh409** [comment]
Go ahead @harshb02

**Comment by harshb02** [comment]
Made the changes kindly review them @harikesh409

**Comment by harikesh409** [comment]
@Khushi-agarwal you can work along with @harshb02

**Comment by Khushi-agarwal** [comment]
> @Khushi-agarwal you can work along with @harshb02
> Just reply to this so that I can assign the issue to you also.

Yes.

**Comment by harshb02** [comment]
> > @Khushi-agarwal you can work along with @harshb02
> > Just reply to this so that I can assign the issue to you also.
> 
> Yes. @harikesh409

Can you please ping me on discord Harsh(P) #8757 @Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
@harikesh409 created a PR #314, kindly review it.
