### ISSUE TITLE
Styling of hover should be changed for "Back-to-top" button

### ISSUE THREAD

**Issue by Shruti3004** [Algo-Phantoms/Algo-Phantoms-Frontend#28]
![Screenshot from 2021-02-27 03-38-44](https://user-images.githubusercontent.com/56133783/109360618-8d495200-78ad-11eb-80ac-f2687adb47d1.png)

**Comment by akashbwj** [comment]
I want to work on this issue as a part of GSSOC'21

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by Avnish5** [comment]
I am doing web dev from last 1 year.
I am also selected as a participant under GSSOC 2021.
Kindly assign this task to me.

**Comment by ashusharma-cs** [comment]
Can I contribute to this issue?

**Comment by akashbwj** [comment]
I want to work on this issue as a part of GSSOC'21

**Comment by Devenkapoor7303** [comment]
Is this issue open for all?? If not can i work on this issue

**Comment by sayna3311** [comment]
I would love to contribute to this issue, under GSSoC'21.

**Comment by Shivam-Shandilya1** [comment]
Hey!!! I want to give assisstance to your nice project as a GSSOC participany?

**Comment by Shivam-Shandilya1** [comment]
Heyy!!! I want to give assisstance to your nice project as a GSSOC participant?

**Comment by gritika18** [comment]
I'm a GSSOC participant and I would like to work on this issue. Could you please assign it to me?

**Comment by Pramit29** [comment]
I am a GSSoc participant and want to work on this issue. I have started learning HTML and CSS so would be able to contribute to this project.

**Comment by harikesh409** [comment]
Issue has been resolved in #56
