### ISSUE TITLE
Improving the UI of DSA Problems page

### ISSUE THREAD

**Issue by ishwari20** [Algo-Phantoms/Algo-Phantoms-Frontend#281]
## Proposal

The UI of the DSA problems page should be improved.  Currently, it just displays the excel sheet on the right side.  It can be aligned in the center and some components can be added on that page to make it attractive.

**Comment by ishwari20** [comment]
I would like to work on this issue. Please assign me with it.

**Comment by ishwari20** [comment]
@ravikr126 @harikesh409 Please assign it to me. I want to work on this issue. I have made changes in my local computer.

**Comment by ravikr126** [comment]
Hii @ishwari20 someone already work on it.so it hard for me to assign this issue to you.I like your interest toward this issues .May be you can collaborate with that person who work on this issue.
