### ISSUE TITLE
No Linting rules present.

### ISSUE THREAD

**Issue by shruti-mayank** [Algo-Phantoms/Algo-Phantoms-Frontend#282]
~~Uniformity in the indentation of the footer section along with the hover effects will make the footer section look more beautiful.~~

Linting rules can be used to maintain a standard indentation across the project.

**Comment by harikesh409** [comment]
As many participants are new to open source and are participating simultaneously maintaining standard  indentations is difficult. A solution will be having Prettier and ESLint rules and performing an automated check on it. Tell us if you are interested in creating linting configurations, if not I will raise it in a new issue.
Hover effects are already being created in #253

**Comment by shruti-mayank** [comment]
> As many participants are new to open source and are participating simultaneously maintaining standard indentations is difficult. A solution will be having Prettier and ESLint rules and performing an automated check on it. Tell us if you are interested in creating linting configurations, if not I will raise it in a new issue.
> Hover effects are already being created in #253

Yeah sure, I can work on linting configurations.

**Comment by harikesh409** [comment]
Go ahead @shruti-mayank

**Comment by shruti-mayank** [comment]
> Go ahead @shruti-mayank

Okay, thank you

**Comment by harikesh409** [comment]
Any progress @shruti-mayank

**Comment by harikesh409** [comment]
Moved to #497
