### ISSUE TITLE
Adding Favicon to all pages and including an ico file

### ISSUE THREAD

**Issue by cryptofox17** [Algo-Phantoms/Algo-Phantoms-Frontend#283]
## **Is your feature request related to a problem? Please describe.**

The favicon is not present on two pages namely DSA problems and Roadmap to DSA. This is because the link tag to display the favicon has not been added to these pages. Also, there is no .ico file present which is the recommended file type for most browsers to include favicon. 

[Analysis of the issue](https://realfavicongenerator.net/favicon_checker?protocol=https&site=algo-phantoms.github.io/Algo-Phantoms-Frontend/)

## **Describe the solution you'd like**

I would like to add the favicon to all the html files and also include ico file.

**Comment by harikesh409** [comment]
Go ahead @cryptofox17
