### ISSUE TITLE
Links missing on some problems

### ISSUE THREAD

**Issue by satcasm** [Algo-Phantoms/Algo-Phantoms-Frontend#284]
In the DSA problems section some problems are missing their links.
Would like to add them under GSSOC' 21.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/112833276-238eb480-90b4-11eb-92a9-f13bfba27ee6.png)
![image](https://user-images.githubusercontent.com/56315878/112833311-2ee1e000-90b4-11eb-8470-9e8dfa622de5.png)

**Comment by harikesh409** [comment]
Go ahead @satcasm

**Comment by satcasm** [comment]
Hey @harikesh409 , can you tell me how do I make changes in the spreadsheet? I am not getting any option.

**Comment by harikesh409** [comment]
> Hey @harikesh409 , can you tell me how do I make changes in the spreadsheet? I am not getting any option.

Ask @Snehakri022 to grant editor permissions for the sheet.

**Comment by satcasm** [comment]
Hey @Snehakri022 would be kind enough to give me editor permissions.

**Comment by prajjwal1231** [comment]
Hey @Snehakri022 @harikesh409 i would like to contribute in this issue ? can you assign it to me ?

**Comment by harikesh409** [comment]
> Hey @Snehakri022 @harikesh409 i would like to contribute in this issue ? can you assign it to me ?

It is already being worked by @satcasm

**Comment by Snehakri022** [comment]
> Hey @Snehakri022 would be kind enough to give me editor permissions?

yeah sure

**Comment by satcasm** [comment]
@Snehakri022 apologies for late response.
I am not getting how to edit it exactly , I mean I am guessing that I would have to go to the URL of the spreadsheet and edit from there, but I am not getting any edit option there. So can you tell me the exact link?

**Comment by Snehakri022** [comment]
https://docs.google.com/spreadsheets/d/1h-RYH9fw98Ls4HpFOSuBQGdyPMY-ZSU3/edit#gid=21324302

use this link

**Comment by satcasm** [comment]
@Snehakri022 thanks , I have made the changes. As no PR can be made for this, I guess that's it for this issue or is there anything else?

**Comment by ravikr126** [comment]
sorry, @satcasm our PA said that no need for this page .we will remob=ving this page from the website .so you can work on a different issues.
