### ISSUE TITLE
[navbar] Bouncing effect in navbar

### ISSUE THREAD

**Issue by bajajanjana** [Algo-Phantoms/Algo-Phantoms-Frontend#287]
I m Gssoc'21 participant. I want to add an effective feature in navbar.
Explanation- On scrolling, the navbar will bounce upside and will disappear for a moment and then will be visible again.
I'll be doing this using javascript.
@Shruti3004  @harikesh409 @ravikr126 please assign this issue to me.

**Comment by Shruti3004** [comment]
Sure, go ahead @bajajanjana

**Comment by bajajanjana** [comment]
Thanks @Shruti3004

**Comment by bajajanjana** [comment]
@Shruti3004 @harikesh409 @ravikr126 I have made PR #289 to solve this issue #287. Please review it.
