### ISSUE TITLE
Close navbar when "About" section opens (in phone view)

### ISSUE THREAD

**Issue by ishwari20** [Algo-Phantoms/Algo-Phantoms-Frontend#288]
## **Is your feature request related to a problem? Please describe.**

- When we open the website on phone and in the navbar click on "About" it scrolls down but the navbar doesn't go away so it overlaps on some of the other elements.

## **Describe the solution you'd like**

- Make the navbar go away when clicked on the "About" section and scroll down to that section.

**Comment by ishwari20** [comment]
@ravikr126 @harikesh409 Please assign it to me. I want to work on this issue. I have made changes in my local computer.

**Comment by harikesh409** [comment]
Go ahead @ishwari20
