### ISSUE TITLE
Implement a preloader

### ISSUE THREAD

**Issue by Shruti3004** [Algo-Phantoms/Algo-Phantoms-Frontend#29]

**Comment by Ankita297** [comment]
can i work on this ?

**Comment by Shruti3004** [comment]
Yours @Ankita297

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by Shruti3004** [comment]
Hy @chehak123, currently @Ankita279 is working on this issue. You can look for the issues which are not assigned to anyone yet or you can open new issues and can start working on it.

**Comment by Ankita297** [comment]
can you add the GGSOC label ?
I have made a PR .Please review it .

**Comment by Ankita297** [comment]
Can you please add the GSSOC label?
I have made a PR .Please review it .

**Comment by padmajabhol** [comment]
I want to add a preloader.

**Comment by 435akashjha** [comment]
Can you provide it to me I will contribute to this

**Comment by sandra9711** [comment]
I would like to contribute to this issue as a gssoc'21 participant. Kindly assign this to me.
