### ISSUE TITLE
Style the button on "Roadmap to your DSA" page

### ISSUE THREAD

**Issue by ishwari20** [Algo-Phantoms/Algo-Phantoms-Frontend#292]
## **Is your feature request related to a problem? Please describe.**

- The current button is very simple and doesn't go with the theme of the website

## **Describe the solution you'd like**

- Style the button according to the theme of the website

**Comment by ishwari20** [comment]
@Shruti3004 Please assign this issue to me. I want to work on it.

**Comment by harikesh409** [comment]
Duplicate of #185 #206
