### ISSUE TITLE
Dynamic Page title for teams page

### ISSUE THREAD

**Issue by Shruti3004** [Algo-Phantoms/Algo-Phantoms-Frontend#30]
Title as Algo Phantoms | Team

**Comment by satcasm** [comment]
Hi, would like to work on this under GSSOC' 21.
Thanks.

**Comment by Shruti3004** [comment]
Go ahead @satcasm

**Comment by satcasm** [comment]
Should I wait till 8th march ? As on that day GSSOC' 21 coding period starts or should I start now?
Thanks.

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21
