### ISSUE TITLE
aligning the contents of navbar in the center

### ISSUE THREAD

**Issue by 123mansha** [Algo-Phantoms/Algo-Phantoms-Frontend#309]
## **Describe the bug**

- The links in the small and medium screen are on the extreme right of the page which does not look good. 

## **Possible solution**

-The links can be aligned in the center.

## **Screenshots**

- **BEFORE**
![Screenshot (9)](https://user-images.githubusercontent.com/59260493/113248464-abee9e80-92da-11eb-97f7-5b1103256dc1.png)

**AFTER**
![Screenshot (10)](https://user-images.githubusercontent.com/59260493/113248500-ba3cba80-92da-11eb-8e30-61f13ecbc105.png)

**Comment by 123mansha** [comment]
@anubhavitis a@harikesh409 please check this and assign me if this isue is relevant

**Comment by ravikr126** [comment]
YOU CAN WORK NOW @123mansha AND USE SOILD BACKGROUND

**Comment by 123mansha** [comment]
okk

**Comment by 123mansha** [comment]
@harikesh409  @ravikr126  
Should I swap the positions of **MORE** and **CONTACT** ?(should **More** be below the **Contact**)

**Comment by ravikr126** [comment]
Yes you can swap and add solid background color to nav bar

**Comment by harikesh409** [comment]
> @harikesh409 @ravikr126
> Should I swap the positions of **MORE** and **CONTACT** ?(should **More** be below the **Contact**)

If the dropdown values are not being hidden inside the scroll bar you can swap them.

**Comment by 123mansha** [comment]
Please review #335 and tell me if any changes are required.

I did not swapped the **MORE** and **CONTACT** as the contents of the dropdown were being hidden by the scroll bar.

**Comment by 123mansha** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/59260493/113502390-b5ca0900-9549-11eb-81a8-eb986e490373.png)


Is this OK or any changes are required

**Comment by 123mansha** [comment]
updated PR #335  please check
@harikesh409

**Comment by 123mansha** [comment]
resolved the conflicts PR #335  
please check @harikesh409  and @ravikr126
