### ISSUE TITLE
SEOs

### ISSUE THREAD

**Issue by Shruti3004** [Algo-Phantoms/Algo-Phantoms-Frontend#31]
Add various meta tags required for it boost up the rating using lighthouse, pageinsights

**Comment by maanpatel2492** [comment]
I would like to work on this issue

**Comment by Shruti3004** [comment]
Go ahead @maanpatel2492

**Comment by parthpandyappp** [comment]
@Shruti3004 If you feel it's been a long time for this issue, feel free to assign me.

**Comment by raks924** [comment]
@Shruti3004 can i work on it?

**Comment by harikesh409** [comment]
> @Shruti3004 can i work on it?

It is already being worked in #46 by @maanpatel2492, @raks924 you can work on some other issue.
