### ISSUE TITLE
Follow us button

### ISSUE THREAD

**Issue by tier3guy** [Algo-Phantoms/Algo-Phantoms-Frontend#311]
@harikesh409 sir in the follow us button , the transition are too fast and its not looking good , can I work on that and enhance the transition effect .

please assign me this so that I can work on that.

**Comment by harikesh409** [comment]
Can you post some screenshots on how you want to change it?

**Comment by Khushi-agarwal** [comment]
Can I work on this issue.I will create a hover effect on the icons.
@harikesh409 @ravikr126

**Comment by harikesh409** [comment]
Duplicate of #307
