### ISSUE TITLE
Social Media Tab

### ISSUE THREAD

**Issue by tier3guy** [Algo-Phantoms/Algo-Phantoms-Frontend#312]
@harikesh409  The social media tab section is hiding behind the logo in the footer section .

The  Issue
![2021-04-01 (2)](https://user-images.githubusercontent.com/73595465/113285885-18809200-9309-11eb-986a-212d67e22784.png)

Can you please guide that how can I fix this .

**Comment by harikesh409** [comment]
Duplicate of #226 #179
