### ISSUE TITLE
Responsiveness for Mobile Phones

### ISSUE THREAD

**Issue by tier3guy** [Algo-Phantoms/Algo-Phantoms-Frontend#313]
@harikesh409 The design is responsive for tablet screen or above devices but not for the mobile phone devices or smaller screens . Please assign me this issue so that I can work on UI of the smaller devices .

issue : 
![2021-04-01 (4)](https://user-images.githubusercontent.com/73595465/113286912-72358c00-930a-11eb-8726-7a2eef476362.png)

**Comment by harikesh409** [comment]
There are already many issues related to the footer responsiveness. #95 #65
