### ISSUE TITLE
Separate contact us page

### ISSUE THREAD

**Issue by Nirpendra09** [Algo-Phantoms/Algo-Phantoms-Frontend#315]
The contact option only has an email option. To increase the scope of contact we can implement a new contact us page where response can be sent through a FORM.
Also there will be social media handle links to contact on specific platform .
 And a bit of animation will make it more awesome.

Please assign me this issue.
 /assign

**Comment by ravikr126** [comment]
someone already works on this issue @Nirpendra09 .i like your sprit but you need to choose new issue or create a new one on a different topic
