### ISSUE TITLE
Add a Footer

### ISSUE THREAD

**Issue by pro-vider** [Algo-Phantoms/Algo-Phantoms-Frontend#316]
## Proposal

Hii, I am a GSSOC'21 participant,I want to add a footer to this page connected with navbar.

**Comment by harikesh409** [comment]
@pro-vider To which page you want to add the footer?

**Comment by pro-vider** [comment]
I want to connect RoadMap to DSA page and DSA problem page by a footer or a button..
It helps the programmer and looks more easy to handle.

**Comment by pro-vider** [comment]
Or we can add the same footer which is used in home page to Roadmap to DSA page and DSA problem page.

**Comment by harikesh409** [comment]
Go ahead @pro-vider 
Add the same footer that is present in the home page.

**Comment by srishtij2000** [comment]
Can I work on this issue?
