### ISSUE TITLE
Implementing Dark theme for the site

### ISSUE THREAD

**Issue by Shruti3004** [Algo-Phantoms/Algo-Phantoms-Frontend#32]

**Comment by saaiswetha** [comment]
I would like to contribute to this issue, am a part of GSSoC'21.

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by maanpatel2492** [comment]
Hey,I would like to implement a dark theme. I added it to my personal project so I have some what idea about it.
(under GSSOC'21)

**Comment by Shruti3004** [comment]
Go ahead @saaiswetha

**Comment by saaiswetha** [comment]
1. Can I add a button (say at the top right corner of the website) to toggle between the 2 themes ??
2. Should the overall theme change to dark or only changes the about section?

**Comment by Shruti3004** [comment]
@saaiswetha yes please add the toggle button on the top and i would suggest overall theme should change to dark.

**Comment by yashsehgal** [comment]
I would also love to contribute to this issue.

**Comment by saaiswetha** [comment]
@Shruti3004 I've made a pull request, could you review it & let me know the changes for the same.

**Comment by mohammedjameel24** [comment]
please assign me this issue

**Comment by ravikr126** [comment]
> @Shruti3004 I've made a pull request, could you review it & let me know the changes for the same.

pull request number??

**Comment by saaiswetha** [comment]
#48

**Comment by saaiswetha** [comment]
> > @Shruti3004 I've made a pull request, could you review it & let me know the changes for the same.
> 
> pull request number??

#48
