### ISSUE TITLE
Newsletter from Algo-Phantoms subscription column 

### ISSUE THREAD

**Issue by shrishti-c** [Algo-Phantoms/Algo-Phantoms-Frontend#320]
A feature to let user subscribe to get monthly newsletter from Algo-Phantoms.

**Comment by harikesh409** [comment]
How are you planning to implement it?

**Comment by shrishti-c** [comment]
We can have at section of newsletter in "more"  column which will land to other page. There we will tell people about perks of hearing from us monthly regarding latest technology and ask them to submit email id. Then in backend part we store those id. For the time being with the help of latest softwares, newsletter could be sent then.

**Comment by harikesh409** [comment]
As of now it is not needed.
