### ISSUE TITLE
adding navbar in DSA page

### ISSUE THREAD

**Issue by Marim99** [Algo-Phantoms/Algo-Phantoms-Frontend#321]
There is no navbar in DSA page , there is only one button in down take you bake to home page .I want to add a navbar to this page .as a participant of GSSOC'21. Please assign it to me
![Screenshot (165)](https://user-images.githubusercontent.com/78925756/113448730-ac7f5600-93fc-11eb-9646-575e533024b5.png)

**Comment by ravikr126** [comment]
someone already raised this issue
