### ISSUE TITLE
Creating a FAQ section

### ISSUE THREAD

**Issue by harshb02** [Algo-Phantoms/Algo-Phantoms-Frontend#326]
I want to create a FAQ section which contains frequently asked questions regarding Algorithm

**Comment by ravikr126** [comment]
you can work now @harshb02

**Comment by harshb02** [comment]
Assign me this issue @ravikr126 @harikesh409

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by harikesh409** [comment]
> Can I work on this issue?

It is already being worked by @harshb02, you can choose some other issue.
