### ISSUE TITLE
Nav bar brand Redirection on Team.html Page

### ISSUE THREAD

**Issue by maneprajakta** [Algo-Phantoms/Algo-Phantoms-Frontend#33]
On the Team.html page when we click on Algo Phantoms (nav-bar brand) is doesn't redirect to the Home page.

**Comment by Shruti3004** [comment]
Go ahead @maneprajakta

**Comment by maneprajakta** [comment]
Sure will work on this issue @Shruti3004  :+1:

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by ravikr126** [comment]
what is your progress @maneprajakta ???

**Comment by maneprajakta** [comment]
@ravikr126 I had made PR for this #36 . It's merged you can close this issue
