### ISSUE TITLE
Navbar alignment

### ISSUE THREAD

**Issue by Khushi-agarwal** [Algo-Phantoms/Algo-Phantoms-Frontend#331]
The nabber alignment is different as the contact us and more should have their positions interchanged and also on scrolling the navbar can be made of solid color instead of being transparent.

Please @harikesh409  , @ravikr126 assign this issue to me.

**Comment by ravikr126** [comment]
You can work on it @Khushi-agarwal

**Comment by harikesh409** [comment]
It is already being worked at https://github.com/Algo-Phantoms/Algo-Phantoms-Frontend/issues/309#issuecomment-812882718
