### ISSUE TITLE
Adding GitHub issue templates

### ISSUE THREAD

**Issue by maneprajakta** [Algo-Phantoms/Algo-Phantoms-Frontend#34]
Hi :)
Right now there is no issue template for Project.
I think we should take advantage of GitHub’s support for multiple issue templates.

You can see here : 
![64684565-3c595a00-d47d-11e9-8ea4-589cffa16375](https://user-images.githubusercontent.com/57425995/109375319-d6b39480-78e1-11eb-9a72-3c14118cde19.png)

I think right now two templates for creating an issue will do great.
1.For bug report 
2.For feature request

Like this :
![Screenshot from 2021-02-27 09-53-01](https://user-images.githubusercontent.com/57425995/109375368-3f9b0c80-78e2-11eb-88bf-ab9dc5464f3d.png)

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by ravikr126** [comment]
this issue is not for GSSOC standard.
