### ISSUE TITLE
Custom Scroll-Bar absent in DSA Problems page

### ISSUE THREAD

**Issue by DEEPIKA-SUK** [Algo-Phantoms/Algo-Phantoms-Frontend#344]
## **Describe the bug**

Custom Scroll bar is absent in **DSA Problems** page, in rest of the pages it is present. I would like to add the same custom scroll bar(feature) in this page also.

## **Possible solution**
I would like to add the same custom scroll bar(feature) in this page also.

## **Screenshots**

![Screenshot (141)_LI](https://user-images.githubusercontent.com/64724039/113555421-8930f280-9618-11eb-8a48-1a2ed9e96388.jpg)

Kindly assign me this issue as a part of GSSOC21.

**Comment by vedant-jain03** [comment]
I want to work on this issue.
