### ISSUE TITLE
Skills Enhancement Table is not aligned Center

### ISSUE THREAD

**Issue by vedant-jain03** [Algo-Phantoms/Algo-Phantoms-Frontend#346]
## **Describe the bug**

- Skills Enhancement Table is not aligned Center

## **Possible solution**

- I have inspect website and it should changed its margin-left to 100px

## **Screenshots**

![bandicam 2021-04-05 21-01-52-038](https://user-images.githubusercontent.com/76901313/113592522-e77ac700-9652-11eb-963b-2fdea2d562df.jpg)

**Comment by harikesh409** [comment]
Go ahead @vedant-jain03.

Suggestion: Try to use rem instead of px, I think so 5rem will be sufficient.

**Comment by vedant-jain03** [comment]
Ya sure @harikesh409 thankyou for suggestion
If you dont mind can you please make me assigned so that other participant will not get confused
And I have also listed more issue if you think it is valid please review it and give me feedback

**Comment by vedant-jain03** [comment]
Thankyou for assingning @harikesh409
