### ISSUE TITLE
Adding Pull Request Template

### ISSUE THREAD

**Issue by maneprajakta** [Algo-Phantoms/Algo-Phantoms-Frontend#35]
It will be super easy to see the changes made by a pull request on Project before merging it through a pull request template.
I think the project should have one.  

Smple PR template :

![Screenshot from 2021-02-27 10-18-57](https://user-images.githubusercontent.com/57425995/109375784-57c05b00-78e5-11eb-8088-0e8ecbd47f29.png)

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by Ankita297** [comment]
Can i work on this issue under GSSOC 21?

**Comment by subhangi2731** [comment]
assign me this please?

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by harikesh409** [comment]
@maneprajakta go ahead
