### ISSUE TITLE
Adding a meta tag to /index.html

### ISSUE THREAD

**Issue by Diksha-11** [Algo-Phantoms/Algo-Phantoms-Frontend#354]
## Proposal

I'm a GSsoc'21 participant and i would like to add a meta tag that conatains http-equiv and content attribute.

As "http-equiv" attribute set  is similar to the  http header. Thus, It should be there in /index.html

Thus I request maintainers to please assign me this issue

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by ravikr126** [comment]
I think someone already opens this issue. but you can work on this because they didn't respond so work on it.
