### ISSUE TITLE
Blue circle in teams section

### ISSUE THREAD

**Issue by nandita658** [Algo-Phantoms/Algo-Phantoms-Frontend#355]
## **Describe the bug**

There is this big blue circle in team section, which is not looking nice. I don't know its purpose, but I think that it would look nice without it.

## **Possible solution**

I have use inspection tool and it can be removed by removing division with class round1.

## **Screenshots**
![Algo Phantoms_Team - Google Chrome 06-04-2021 16_20_14](https://user-images.githubusercontent.com/65300305/113702010-90c6c900-96f6-11eb-9d08-b6f62edcf167.png)

**Comment by ravikr126** [comment]
someone already create this issue
