### ISSUE TITLE
Changing the height and color of teams section

### ISSUE THREAD

**Issue by cryptofox17** [Algo-Phantoms/Algo-Phantoms-Frontend#356]
## **Is your feature request related to a problem? Please describe.**
The teams section is way too big and occupies much of the screen even though the content doesn't require it. Also the background colors blends in with the footer color so there is no seperation between the two. 

## **Describe the solution you'd like**

- Changing the height of the section
- Choosing different background color to make the page look more homogenous

I would like to work on this issue.

**Comment by ravikr126** [comment]
someone already work on it .please work on different issues.
