### ISSUE TITLE
remove team section from home page

### ISSUE THREAD

**Issue by ravikr126** [Algo-Phantoms/Algo-Phantoms-Frontend#358]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by harshb02** [comment]
I want to work on this issue @ravikr126

**Comment by ravikr126** [comment]
you can work now @harshb02

**Comment by simranbhalla3** [comment]
I am a Gssoc participant, Can i work on this issue?

**Comment by ritesh1731** [comment]
I would like to work on this issue as a GSSOC21 Participant. Can you please assign it to me?

**Comment by harsh725** [comment]
I want to work on this project.
