### ISSUE TITLE
Hover effect to Sharpen your skills section

### ISSUE THREAD

**Issue by shonali2600** [Algo-Phantoms/Algo-Phantoms-Frontend#361]
## **Is your feature request related to a problem? Please describe.**

The Hovering effect added to sharpen your skills section is not looking good and may irritate the user.

## **Describe the solution you'd like**

I would like to make it look better.

**Comment by shonali2600** [comment]
Please assign this issue to me as a gssoc participant.

**Comment by ravikr126** [comment]
you can work now and also align this section at the center @shonali2600

**Comment by shonali2600** [comment]
Thanks for assigning me this issue, but it's already aligned at the center
