### ISSUE TITLE
FAQs are very much congested

### ISSUE THREAD

**Issue by shonali2600** [Algo-Phantoms/Algo-Phantoms-Frontend#362]
## Proposal

The FAQs written are very much congested and not looking good with a very large font and not so good font style.

I would like to improve its appearance by designing it good, changing font style and size.

**Comment by shonali2600** [comment]
Please assign this issue to me as a gssoc participant

**Comment by ravikr126** [comment]
this section will further enhance by assign participant so I think you need to work on a different issues. @shonali2600

**Comment by shonali2600** [comment]
@ravikr126 so sorry but I didn't get you what you are trying to say, no one has created similar issue.

**Comment by ravikr126** [comment]
come to discord server @shonali2600
