### ISSUE TITLE
Links to be added on the Sharpen your skills section

### ISSUE THREAD

**Issue by sohini3062** [Algo-Phantoms/Algo-Phantoms-Frontend#363]
## Proposal
currently the sharpen your skills sections contains data structure, algorithms,python sections etc which on being clicked revert back to the home page. Topic Specific GeekforGeeks links can be added to them, for example [Link](https://www.geeksforgeeks.org/data-structures) be added for data structures.
(A clear and concise description of what the proposal is.)

**Comment by ravikr126** [comment]
we are planning to add some own content .so adding third parties links will not require.
this is future enhancement so I think it will need some time to implementation

**Comment by sohini3062** [comment]
Okay sure!
