### ISSUE TITLE
"Suggested Books" in the "More" tab of navbar not showing on the Teams page

### ISSUE THREAD

**Issue by sakshigoel19** [Algo-Phantoms/Algo-Phantoms-Frontend#365]
## **Describe the bug**
Navbar contents should be consistent on all pages but on the navbar of teams page - on the more tab - suggested books option is not showing as it is on the home page. I want to fix this. Please assign me this under GSSOC'21.

## **Possible solution**
I will add "Suggested Books" on the More tab of teams page that will redirect to the booklist page.

## **Screenshots**
On Home Page-
![image](https://user-images.githubusercontent.com/61665348/113887309-03ab6f00-97df-11eb-92fa-a7ed9ead13d7.png)
 On Teams page- 
![image](https://user-images.githubusercontent.com/61665348/113887451-1f167a00-97df-11eb-95c7-8a938c5db106.png)

**Comment by Muskan-creator** [comment]
I want to work on this issue please assign me this issue @harikesh409

**Comment by sakshigoel19** [comment]
@ravikr126 Please assign it to me.

**Comment by ravikr126** [comment]
ok @sakshigoel19 you can work on this

**Comment by harikesh409** [comment]
What is the progress @sakshigoel19

**Comment by sakshigoel19** [comment]
Please give some more time.Having some emergency at home because of covid situation.

**Comment by harikesh409** [comment]
> Please give some more time.Having some emergency at home because of covid situation.

Okay, take care of your health.

**Comment by raks924** [comment]
hey @harikesh409 @ravikr126 i really want to merge a few PRs .can i work on this issue?

**Comment by ravikr126** [comment]
Let me.talk.to the participate if she not work then i will assignment you @raks924

**Comment by sakshigoel19** [comment]
Sorry for the delay. I will make a PR by today or max tomorrow. After tomorrow, you can assign to anybody else.
