### ISSUE TITLE
Links added twice

### ISSUE THREAD

**Issue by tanishq-arya** [Algo-Phantoms/Algo-Phantoms-Frontend#369]
## **Describe the bug** 
Please assign it to me under gssoc
Project ideas link is added twice
## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot (1126)_LI](https://user-images.githubusercontent.com/77333275/113995654-10c66d80-9874-11eb-8e95-4b4dc400db8d.jpg)

**Comment by Jagannath8** [comment]
Assign it to me.

**Comment by ravikr126** [comment]
you can work on it and also remove DSA Guidance link @tanishq-arya
