### ISSUE TITLE
Suggestion: uppercase in team.html

### ISSUE THREAD

**Issue by javpintos** [Algo-Phantoms/Algo-Phantoms-Frontend#37]
Suggestion: uppercase in team.html
(testing issues and PR in GH)

**Comment by maanpatel2492** [comment]
Kindly tell me about this issue. I will solve it.

**Comment by ravikr126** [comment]
any progress @javpintos ????

**Comment by harikesh409** [comment]
> Kindly tell me about this issue. I will solve it.

Check changes on #38 if interested tell me I will assign it to you.

**Comment by ShrutiKhatri826** [comment]
I would like to contribute to this issue as a GSSOC'21 participant. Please assign it to me, hoping for a positive reply soon.

**Comment by harikesh409** [comment]
> I would like to contribute to this issue as a GSSOC'21 participant. Please assign it to me, hoping for a positive reply soon.

Go ahead, check the requested changes in #38.
