### ISSUE TITLE
Aligning the Sharpen Your Skills Section to center

### ISSUE THREAD

**Issue by tarunsinghofficial** [Algo-Phantoms/Algo-Phantoms-Frontend#373]
## Bug

The alignment of the Sharpen Your Skills is not centered.

## **Solution**

I can fix this issue. Please assign this issue to me! I am a GSSoC participant

## **Screenshots**

![image](https://user-images.githubusercontent.com/62840625/114063048-d2ea3900-98b5-11eb-82cd-a92a1eac59bc.png)

**Comment by raks924** [comment]
hey i would like to work on this issue. Please assign this to me.

**Comment by ravikr126** [comment]
you can work on it and also add hover effect on c,c++ and java section @tarunsinghofficial
