### ISSUE TITLE
About section overlapping the social sidebar (phone view)

### ISSUE THREAD

**Issue by ishwari20** [Algo-Phantoms/Algo-Phantoms-Frontend#374]
## **Describe the bug**

- The about section overlapping the social sidebar in phone view

## **Possible solution**

- Work on the z-index

## **Screenshots**

![Screenshot (167)](https://user-images.githubusercontent.com/56400099/114134327-2d6eae00-9925-11eb-9799-ffebc2b3e144.png)

**Comment by ishwari20** [comment]
@harikesh409 @ravikr126 Please assign it to me, I have made changes in my local computer

**Comment by ravikr126** [comment]
Please come to discord server and tag me

**Comment by ishwari20** [comment]
@ravikr126 Done!

**Comment by ravikr126** [comment]
you need to do too many changes in mobile view there is a lot of bugs in the mobile view 
see some ss that i have taken .you can raise extra issues or join today meeting at 7 .link will provide on discord server
![algo-phantoms github io_Algo-Phantoms-Frontend_booklist html](https://user-images.githubusercontent.com/53082978/114270037-c4239380-9a27-11eb-88e3-f83f7532982e.png)

**Comment by ravikr126** [comment]
you can work now @ishwari20
