### ISSUE TITLE
Want to add Theme Change Button in Navigation menu 

### ISSUE THREAD

**Issue by divyanshkhatana** [Algo-Phantoms/Algo-Phantoms-Frontend#376]
Hello, I want to add a sliding theme changing button to navigation bar ,which can be changed to black theme or white theme.

Given below is sliding button for your reference .
![image](https://user-images.githubusercontent.com/44130452/114162590-dda0de80-9946-11eb-8224-08428c914c24.png)

I want to work on this issue @ravikr126

**Comment by iaryangoyal** [comment]
kindly assign this work to me

**Comment by Shivangi-ch** [comment]
Assign this to me.

**Comment by ravikr126** [comment]
why you think about darks theme .there is already a website in the dark color @divyanshkhatana

**Comment by divyanshkhatana** [comment]
@ravikr126  there will be option between dark and light theme not just only dark.

**Comment by ravikr126** [comment]
the webpage is already dark video .so i don't think for dark mode @divyanshkhatana
