### ISSUE TITLE
add back to home page button

### ISSUE THREAD

**Issue by shonali2600** [Algo-Phantoms/Algo-Phantoms-Frontend#378]
## **Is your feature request related to a problem? Please describe.**

after opening "Roadmap to DSA" or "DSA Problem" there is no button that provides the functionality to go back to the home page.

## **Describe the solution you'd like**

I would like to add a back button to all these sections or adding the header can also do the needful, please suggest me the best way.

Please assign me this issue as a gssoc participant.

**Comment by ravikr126** [comment]
you can work on it @shonali2600

**Comment by shonali2600** [comment]
@ravikr, please suggest me should I add a header(nav bar) or only a back to home page button?

**Comment by ravikr126** [comment]
please join meet @shonali2600

**Comment by ravikr126** [comment]
add navbars on all pages @shonali2600
