### ISSUE TITLE
Adding the colour of social media icons on hover in the footer of the home page

### ISSUE THREAD

**Issue by Harshit-Pathak** [Algo-Phantoms/Algo-Phantoms-Frontend#383]
<h3>The Issue </h3>
In the footer section the color change on hover over social media icons is same

<h3>Enhancement</h3>
 Adding the respective colors on hovering over social media icons in the footer of the homepage 

Please assign me this issue as a gssoc'21 participant

**Comment by harikesh409** [comment]
Go ahead @Harshit-Pathak

**Comment by Harshit-Pathak** [comment]
> Go ahead @Harshit-Pathak

Ok sir
