### ISSUE TITLE
Making dsa.html responsive.

### ISSUE THREAD

**Issue by kanishka8276** [Algo-Phantoms/Algo-Phantoms-Frontend#386]
Iframe in dsa.html is not responsive as it has absolute dimensions. I will like to make it responsive.
Please assign this to me.

**Comment by ravikr126** [comment]
you can work on it @kanishka8276

**Comment by arpit456jain** [comment]
@kanishka8276 will you work on this issue?

**Comment by kanishka8276** [comment]
@arpit456jain yes.

**Comment by ravikr126** [comment]
any progress @kanishka8276

**Comment by kanishka8276** [comment]
@ravikr126 yes, Actually somebody has made a PR for navbar in dsa.html  so I was waiting for it to be merged.
