### ISSUE TITLE
Revamp using ReactJS

### ISSUE THREAD

**Issue by A7abhilash** [Algo-Phantoms/Algo-Phantoms-Frontend#39]
Going ahead with basic html and vanilla javascript would be a troublesome process as per the features needed. So I would like to completely revamp the site using React JS with minimalistic UI using bootstrap and framer motion and then go ahead for adding the features mentioned(code editor and quiz).

#GSSOC'21

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this...
-gssoc'21 participant

**Comment by A7abhilash** [comment]
@ShambhaviSharma0110 @subhangi2731 I've already done the revamping and tested thoroughly in localhost.
But when I hosted it(frontend on netlify and backend on heroku) for demo, I wasnt able to get the auth token from backend.
IDK why it is happening so? If you guys know how to resolve that then please help me.
Once it get merged then we all can go ahead with adding more features for this MERN App.
[Repo for revamped app](https://github.com/A7abhilash/BlogSite/tree/develop)

**Comment by A7abhilash** [comment]
@subhangi2731 @ShambhaviSharma0110 I have been asking the mentors about this but there is no response from them... I asked them even on discord also but still they just ignored my suggestion!!!
