### ISSUE TITLE
Aligning and improving the Sharpen your skills section in the mobile view

### ISSUE THREAD

**Issue by harshb02** [Algo-Phantoms/Algo-Phantoms-Frontend#391]
The Sharpen your skills section in the mobile view is not aligned properly and is creating a problem in the mobile view

I want to make it correct so kindly assign this issue to me @ravikr126 @harikesh409

**Comment by ravikr126** [comment]
@harshb02 you can work now

**Comment by shrishti-c** [comment]
![Screenshot (157)](https://user-images.githubusercontent.com/73748606/114825684-298ad200-9de4-11eb-9f78-72d21743e0ca.png)
Where is these section that you are working on? I couldn't find them

**Comment by harikesh409** [comment]
> ![Screenshot (157)](https://user-images.githubusercontent.com/73748606/114825684-298ad200-9de4-11eb-9f78-72d21743e0ca.png)
> Where is these section that you are working on? I couldn't find them

You are viewing an old code pull the latest code then you can get those changes and view it.

**Comment by harikesh409** [comment]
Any progress @harshb02 ?

**Comment by harshb02** [comment]
Already solved the issue @harikesh409

**Comment by harikesh409** [comment]
Closing as it has been resolved.
