### ISSUE TITLE
Social media icons in footer of home page and team page not same

### ISSUE THREAD

**Issue by ishwari20** [Algo-Phantoms/Algo-Phantoms-Frontend#394]
## **Describe the bug**

- The social media icons in the footer section of home page and team page not the same

## **Possible solution**

- Make them same

## **Screenshots**

![Screenshot (172)](https://user-images.githubusercontent.com/56400099/114609766-c5212300-9cbc-11eb-8235-f05d53ba3320.png)
![Screenshot (173)](https://user-images.githubusercontent.com/56400099/114609778-c81c1380-9cbc-11eb-9c72-ab59bba92df0.png)

**Comment by ishwari20** [comment]
@ravikr126 @harikesh409 Please assign it to me. I want to work on this issue

**Comment by ravikr126** [comment]
Ok and check all pages if needed try to improve all pages.@ishwari20
