### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by tanishq-arya** [Algo-Phantoms/Algo-Phantoms-Frontend#397]
## **Describe the bug**

- There is an issue with the script for navbar 

## **Possible solution**
- Add an id nav to the nav element

## **Screenshots**
![Screenshot (1205)](https://user-images.githubusercontent.com/77333275/114660324-bf562c80-9d12-11eb-9b3f-2af4a4423011.png)

**Comment by tanishq-arya** [comment]
Please assign me this issue under gssoc.

**Comment by harikesh409** [comment]
Go ahead @tanishq-arya
