### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by sreetu** [Algo-Phantoms/Algo-Phantoms-Frontend#401]
## **Describe the bug**

- A clear and concise description of what the bug is.
- Text overlaps in mobile view

## **Possible solution**

- Describe the solution you thought of.
- To make text responsive using bootstrap.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot (497)](https://user-images.githubusercontent.com/72204621/114721326-72944500-9d56-11eb-8353-70063be15e64.png)

**Comment by harikesh409** [comment]
Please go ahead @sreetu
