### ISSUE TITLE
Improving practicedsa.html page

### ISSUE THREAD

**Issue by 1vivekanand** [Algo-Phantoms/Algo-Phantoms-Frontend#403]
## Proposal

We can have cards for different topics and  under that there will be list of problems.

**Comment by 1vivekanand** [comment]
assign this issue to me under GSSOC'21

**Comment by harikesh409** [comment]
Can you elaborate a bit more as there is already a topic wise problems list under DSA problems.

**Comment by 1vivekanand** [comment]
when we click on DSA Problems button it opens the list of problems. The present UI is like an excel sheet having all the topics at the same place. what I think is instead of that we can have cards of different topics( eg-> 1 card for Array, another for Linked list or tree and so on) and under that the same problems will be there for that specified topic only in a tabulated manner .In this manner the UI will be pretty good

**Comment by harikesh409** [comment]
A similar suggestion was suggested at https://github.com/Algo-Phantoms/Algo-Phantoms-Frontend/issues/444#issuecomment-825809972 and @ravikr126 has some suggestions on it ping him on discord he can guide you through it.

**Comment by ravikr126** [comment]
Now @ishwari20 you can work on it
