### ISSUE TITLE
Aligning the subtitle part

### ISSUE THREAD

**Issue by shrishti-c** [Algo-Phantoms/Algo-Phantoms-Frontend#405]
The subtitle part "Algo Phantom is an open source........" needs to be aligned in with respect to heading in center.

**Comment by harikesh409** [comment]
I don't see any issue in the alignment on which browser and resolution are you observing this issue and if possible post some screenshots so we can confirm the bug.

**Comment by harikesh409** [comment]
Closing the issue as there is no response from the creator.
