### ISSUE TITLE
Close Navbar when clicked on any button in it (in phone view)

### ISSUE THREAD

**Issue by ishwari20** [Algo-Phantoms/Algo-Phantoms-Frontend#406]
## **Is your feature request related to a problem? Please describe.**

- When we click on the buttons/links in the navbar like contact/about, it just scrolls down in the page but the navbar doesn't close and thus overlaps on the other elements. (in phone view)

## **Describe the solution you'd like**

- Close the navbar on click

**Comment by ishwari20** [comment]
@ravikr126 @harikesh409 Please assign it to me. I want to work on this issue

**Comment by ravikr126** [comment]
ok you can work on it @ishwari20
