### ISSUE TITLE
The Slidebar Icon of Instagram is not correct

### ISSUE THREAD

**Issue by aditidewangan** [Algo-Phantoms/Algo-Phantoms-Frontend#413]
## **Describe the bug**

- The Slidebar Icon of Instagram is not correct.

## **Possible solution**

- I want to change the icon to its correct Instagram icon.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

![WhatsApp Image 2021-04-16 at 5 11 33 PM](https://user-images.githubusercontent.com/76042201/115019610-0ee55580-9ed7-11eb-8d7c-d1e5ff8f2874.jpeg)

**Comment by aditidewangan** [comment]
Please assign me this issue.

**Comment by ravikr126** [comment]
Kya dikkat aai hai ishme?? @aditidewangan

**Comment by aditidewangan** [comment]
The slidebar icon of Instagram is not correct. I would like to change it to its correct icon please assign me this.

**Comment by ravikr126** [comment]
what is the error @aditidewangan

**Comment by harikesh409** [comment]
It is the correct Instagram icon only no need to change it.
