### ISSUE TITLE
Making "more" option in navbar expand on hovering

### ISSUE THREAD

**Issue by shrishti-c** [Algo-Phantoms/Algo-Phantoms-Frontend#414]
We need to click on on more option to expand and collapse. We can enhance it by adding hover effect. This will give a smooth effect to page.

**Comment by ravikr126** [comment]
You can work on it.@shrishti-c

**Comment by harikesh409** [comment]
Any progress @shrishti-c ?

**Comment by harikesh409** [comment]
> can I work on this?

Let's wait for a day and if there is no reply from @shrishti-c then I will assign it to you @Kalashri99

**Comment by ShrutiKhatri826** [comment]
I would like to contribute to this issue as a GSSOC'21 participant. Please assign it to me, hoping for a positive reply soon.

**Comment by Kalashri99** [comment]
> > can I work on this?
> 
> Let's wait for a day and if there is no reply from @shrishti-c then I will assign it to you @Kalashri99

Can you please assign it to me?

**Comment by harikesh409** [comment]
> > > can I work on this?
> > 
> > 
> > Let's wait for a day and if there is no reply from @shrishti-c then I will assign it to you @Kalashri99
> 
> Can you please assign it to me?

Go ahead @Kalashri99

**Comment by Kalashri99** [comment]
[https://github.com/Algo-Phantoms/Algo-Phantoms-Frontend/pull/504#issue-649007695](url)

**Comment by Kalashri99** [comment]
[Kalashri99:algo-Phantoms#414](url)

**Comment by Kalashri99** [comment]
please review PR https://github.com/Algo-Phantoms/Algo-Phantoms-Frontend/pull/504
