### ISSUE TITLE
Proper Positioning of Go Back button

### ISSUE THREAD

**Issue by shrishti-c** [Algo-Phantoms/Algo-Phantoms-Frontend#415]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.
![Screenshot (166)](https://user-images.githubusercontent.com/73748606/115103650-2709b300-9f71-11eb-8976-3b32979182a3.png)

**Comment by ravikr126** [comment]
Someone already work on it @shrishti-c
