### ISSUE TITLE
Enhancing Book List Page

### ISSUE THREAD

**Issue by shrishti-c** [Algo-Phantoms/Algo-Phantoms-Frontend#417]
On hovering over links, link text doesn't contrast with the background. I'll modify color contrast between background and foreground content to ensure legibility
![Screenshot (167)](https://user-images.githubusercontent.com/73748606/115104320-4571ad80-9f75-11eb-81a4-d8bbe0865316.png)

**Comment by ravikr126** [comment]
Someone already work on it @shrishti-c
