### ISSUE TITLE
Add navigator bar to the BookList page

### ISSUE THREAD

**Issue by sohini3062** [Algo-Phantoms/Algo-Phantoms-Frontend#418]
## **Is your feature request related to a problem? Please describe.**
The booklist page does not have a navigation bar. 
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**
I want to add the one present on the main website on booklist page as well.
- A clear and concise description of what you want to happen.

**Comment by ravikr126** [comment]
Someone work on this issue already
