### ISSUE TITLE
About Us Section Enhancement

### ISSUE THREAD

**Issue by AnshikaAgrawal5501** [Algo-Phantoms/Algo-Phantoms-Frontend#420]
## Proposal

The About Us section doesn't look attractive, I would like to enhance its content by adding a related GIF or some image and changing the font family of the text present.

I am a GSSOC participant and would like to work on this issue.

**Comment by ravikr126** [comment]
what you like to implement in about us section? @AnshikaAgrawal5501

**Comment by AnshikaAgrawal5501** [comment]
Hey @ravikr126,
At present the About Us section is having only text, I would like to add an image related to text or coding. 

![Untitled1](https://user-images.githubusercontent.com/56653257/115149802-5e688480-a083-11eb-84d6-66d2d2abe674.png)

As you can see, it's just plain text with no attractiveness. Also, I feel like we should try a different font family which will make the text look better.

**Comment by ravikr126** [comment]
Ok @AnshikaAgrawal5501 you can work on it .

**Comment by AnshikaAgrawal5501** [comment]
Thank you for assigning me this issue.
