### ISSUE TITLE
Roadmap Page 

### ISSUE THREAD

**Issue by AnshikaAgrawal5501** [Algo-Phantoms/Algo-Phantoms-Frontend#421]
## Proposal

I think the Roadmap page needs to be changed completely. We should replace the image of the roadmap with proper text (text taken from image) and we can put proper images related to context.

**Comment by ravikr126** [comment]
ok can you share some ss of this implementation? @AnshikaAgrawal5501

**Comment by AnshikaAgrawal5501** [comment]
I have not prepared anything till now. But I am thinking of making this like the FAQ section not exactly like that but kind of.
There is a list of all the major headings and when we click on that a small note will appear describing that heading.

![screen-capture (1)](https://user-images.githubusercontent.com/56653257/115150243-2feba900-a085-11eb-81b4-042fcb92fc90.gif)


For instance, assume that the first heading is of Prerequisite. When we click on that a short note will appear explaining "any language can be selected but the main focus should be that you are completely comfortable with that." And then there will be some languages name like C, CPP, Java, etc.

In the resources section, we can provide links to the sites. And so on we can convert a complete roadmap to text. And put necessary images if feel needed which will make the readers catch interest in reading.

**Comment by ravikr126** [comment]
Please dm me in discord server.i will share some information there @AnshikaAgrawal5501
