### ISSUE TITLE
Add links to topics given under SHARPEN YOUR SKILLS.

### ISSUE THREAD

**Issue by codebuzzer01** [Algo-Phantoms/Algo-Phantoms-Frontend#427]
## Proposal

The topics which are specified under SHARPEN YOUR SKILLS section redirect to the homepage. Here, I would like to add the links to the topics which will redirect the user to the new webpage consisting the stuffs of the same. So, I would be creating webpages of each topic and add the link for it.
For ex. The 'DATA STRUCTURES' skill given under SHARPEN YOUR SKILLS section will redirect the user to a new webpage which will consist of all the stuffs regarding the same.

**Comment by codebuzzer01** [comment]
hey @ravikr126  shall I work on it??

**Comment by ravikr126** [comment]
yes you can work on it @codebuzzer01
