### ISSUE TITLE
Enhancement in Book List Section

### ISSUE THREAD

**Issue by yashikabhargava** [Algo-Phantoms/Algo-Phantoms-Frontend#431]
### Is your feature request related to a problem? Please describe.

1. The font size of heading is too small, and book list is too large.
2. The background does not match the theme of the website.
3. while hovering the color of link changes that also not visible clearly.
4. currently does not look attractive.

### **Describe the solution you'd like**

1. Change in the font size and font family of text.
2. Change in the background according to the theme of website.
3. Change in font color and addition of box shadow.
4. Change in complete look to make it more attractive.

### Additional Context

I want to work on this issue, can you please assign it to me as participant of GSSOC21.

**Comment by yashikabhargava** [comment]
I am a gssoc21 participant and would like to work on this issue. Can you please assign it to me.

**Comment by ravikr126** [comment]
someone already work on it @yashikabhargava
