### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by vedant-jain03** [Algo-Phantoms/Algo-Phantoms-Frontend#432]
## **Is your feature request related to a problem? Please describe.**

- I want to add night mode feature to the website.

## **Describe the solution you'd like**

- I will make switch toggle button and using javascript I will toggle the Dark mode class in the website sections.

**Comment by vedant-jain03** [comment]
@ravikr126 If valid Please assign me

**Comment by ravikr126** [comment]
no need of night mode on website @vedant-jain03
