### ISSUE TITLE
removal of social side bar in home page 

### ISSUE THREAD

**Issue by ravikr126** [Algo-Phantoms/Algo-Phantoms-Frontend#434]
## **Is your feature request related to a problem? Please describe.**

- remove the social sidebar.it overlaps with every message on mobile view

## **Describe the solution you'd like**

- remove this features

**Comment by ishwari20** [comment]
@ravikr126 I would like to work on it. Please assign it to me

**Comment by ravikr126** [comment]
Ok @ishwari20 you can work on it

**Comment by ishwari20** [comment]
@ravikr126  Is it to be done in phone view only or remove it totally?

**Comment by ravikr126** [comment]
If it possible to remove only in phone view then remove only in phone view .If not then remove from both view @ishwari20

**Comment by ishwari20** [comment]
Okay will do!

**Comment by harshb02** [comment]
This issue has already been raise by you Ravi a week ago. Kindly check the issue #392 @ravikr126
