### ISSUE TITLE
Footer not up to date on Teams Page and Suggested Book Page

### ISSUE THREAD

**Issue by sohini3062** [Algo-Phantoms/Algo-Phantoms-Frontend#436]
GSSOC 2021 PARTICIPANT

## **Describe the bug**
The footer on the teams and Suggested Books page is missing certain links under features.
- A clear and concise description of what the bug is.

## **Possible solution**
Update the footer of both these pages like in the home page.
- Describe the solution you thought of.

## **Screenshots**
Home Page
![1](https://user-images.githubusercontent.com/64258756/115737637-f0d19680-a3a9-11eb-835b-50714503c2bf.JPG)
![tempsnip](https://user-images.githubusercontent.com/64258756/115737652-f333f080-a3a9-11eb-8bcd-cb6ee866109b.png)

- If applicable, add screenshots to help explain your problem.

**Comment by harikesh409** [comment]
Please go ahead @sohini3062
