### ISSUE TITLE
Changing the input type of Email element.

### ISSUE THREAD

**Issue by aniketsingh98571** [Algo-Phantoms/Algo-Phantoms-Frontend#44]
@todi-2000 I saw that the `<input type="text" class="form-control py-3" placeholder="Enter your Email">` `type` of input element for the email is `text` which is not recommended instead we can add `input type="email"`.
And also I suggest it, use Firebase database storage for contact saving or you can just redirect the link to the mailing system using `mailto`.

I would like to go with this issue as part of  GSSoC 2021

**Comment by aniketsingh98571** [comment]
@rudrakshi99 I would like to go with this issue as part of GSSoC 2021

**Comment by DharmikPansuriya** [comment]
Hello @aniketsingh98571, have you solved this issue? Otherwise, I would like to solve!

**Comment by aniketsingh98571** [comment]
@DharmikPansuriya This issue has been resolved and I have raised the PR regarding the same.

**Comment by DharmikPansuriya** [comment]
Okay :) @aniketsingh98571

**Comment by DharmikPansuriya** [comment]
Okay :) @aniketsingh98571

**Comment by raveena69** [comment]
I would like to go with this issue

**Comment by harikesh409** [comment]
Issue already resolved.
