### ISSUE TITLE
Error in last card in team.html

### ISSUE THREAD

**Issue by Aarti002** [Algo-Phantoms/Algo-Phantoms-Frontend#440]
Bottom right card not showing effects on moving cursor around the card like other remaining card does.
Please assign this to me @ravikr126  i will look into it.
Thank You!

**Comment by harikesh409** [comment]
I can't replicate the issue I have tested in chrome, edge and Firefox. Can you specify under which browser and browser version this issue exists?

**Comment by harikesh409** [comment]
Closing the issue as there is no reply from @Aarti002 and cannot be replicated when tested.
