### ISSUE TITLE
Alert message on entering website

### ISSUE THREAD

**Issue by Aarti002** [Algo-Phantoms/Algo-Phantoms-Frontend#441]
Whenever a user visits the website an alert or a kind of welcoming box will pop up from the top.
@ravikr126 shall i work on it?
Thank you!

**Comment by Pushpit07** [comment]
What kind of alert are you talking about?

**Comment by Aarti002** [comment]
i will be using SweetAlert which will just provide option whether user want continue using this website or not , can we send them emails or not?
or if i can add something better i will you know, currently i'm out of options @Pushpit07

**Comment by Aarti002** [comment]
can i work on it? @Pushpit07

**Comment by harikesh409** [comment]
No need of any kinds of alerts on website entering.
