### ISSUE TITLE
Add a welcome bot 

### ISSUE THREAD

**Issue by Ankita297** [Algo-Phantoms/Algo-Phantoms-Frontend#446]
## **Is your feature request related to a problem? Please describe.**

Add a welcome bot using github action like when contributor makes his/her first PR or open his/her first issue  it will greet them .
## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.
![New issue · Issue #1 · Ankita297_Story - Google Chrome 22-04-2021 00_53_11](https://user-images.githubusercontent.com/67833077/115945910-92a4d080-a4db-11eb-987f-074b673bf553.png)

**Comment by harikesh409** [comment]
Already a bot is present greeting all the users on creating an issue you can see the first comment on this issue that is by the github bot only.
