### ISSUE TITLE
Add github link in sidebar

### ISSUE THREAD

**Issue by Mukta-Sawant** [Algo-Phantoms/Algo-Phantoms-Frontend#447]
## **Describe the bug**

- Github sidebar's icon directs to the algo-phantom website whereas the github icon in the footer section directs to the Algo-Phantoms Github repo.

## **Possible solution**

- We can add a link in the sidebar's Github icon too.

**GSSOC'21**

**Comment by harikesh409** [comment]
Please go ahead and add the github link. @Mukta-Sawant
