### ISSUE TITLE
Add github action to auto-message the contributor when their pr is merged

### ISSUE THREAD

**Issue by AB-san** [Algo-Phantoms/Algo-Phantoms-Frontend#450]
## Proposal

(A clear and concise description of what the proposal is.)

Message like -  "Well Done @username !! Looking forward for more such contributions" or any other message as per the mentor's wish 
would be sent to the contributor after their pr is merged successfully

**Comment by AB-san** [comment]
I would like to work on this issue

**Comment by harikesh409** [comment]
It is not needed as mentors will be commenting and on a successful PR merge the github will send an notification.
