### ISSUE TITLE
Add github action to add auto reply whenever a new pr is opened

### ISSUE THREAD

**Issue by AB-san** [Algo-Phantoms/Algo-Phantoms-Frontend#451]
## Proposal

(A clear and concise description of what the proposal is.)
Message like -  " We got your pr !! Please kindly wait for team to review it " or any other message as per the mentor's wish 
would be sent to the contributors when they open a pr

**Comment by AB-san** [comment]
I would like to work on this issue

**Comment by harikesh409** [comment]
Not needed.
