### ISSUE TITLE
Add auto issue labler

### ISSUE THREAD

**Issue by AB-san** [Algo-Phantoms/Algo-Phantoms-Frontend#453]
## Proposal

(A clear and concise description of what the proposal is.)

there are three templates for issues - bug , feature , proposal

How about if we have a github action to add tags(bug tag, feature tag, proposal tag) for the same if similar keywords are present in the issue

**Comment by AB-san** [comment]
i would like to work on this issue

**Comment by harikesh409** [comment]
Most of the participants are new to open sources and may not keep the description with the expected keywords so automating labels is not suggested.

**Comment by AB-san** [comment]
> Most of the participants are new to open sources and may not keep the description with the expected keywords so automating labels is not suggested.

For that we can add a github action which will ask the participant - "Make sure you follow the guidelines/template to create a issue " as soon as they create a new issue . Does that sound good?

**Comment by harikesh409** [comment]
> > Most of the participants are new to open sources and may not keep the description with the expected keywords so automating labels is not suggested.
> 
> Yeah you are right but For that we can add a github action which will ask the participant - "Make sure you follow the guidelines/template to create a issue " as soon as they create a new issue . Does that sound good?

Already templates are present but most of them are just deleting the template and writing it on their own forcing them to follow the template is difficult.
