### ISSUE TITLE
Enhancement animation in About page

### ISSUE THREAD

**Issue by archanagandhi** [Algo-Phantoms/Algo-Phantoms-Frontend#456]
Hey @harikesh409 I would like to add a animation effect to the image in about us page. 

Demo of the animation:

https://user-images.githubusercontent.com/74424757/115984305-015d5900-a5c4-11eb-8991-2500a12686a4.mp4

**Comment by harikesh409** [comment]
Already the home page is heavy loaded so no need of any additional animations.
