### ISSUE TITLE
Image and data not being hidden on page flip in team.html in Firefox browser

### ISSUE THREAD

**Issue by harikesh409** [Algo-Phantoms/Algo-Phantoms-Frontend#457]
## **Describe the bug**
In Firefox browser in `team.html` page on hover of the cards the image and the data is not being hidden as it is being hidden in chrome or edge, refer the screenshots below.

## **Screenshots**
- In Firefox
![image](https://user-images.githubusercontent.com/3501554/115985187-4edbc500-a5c8-11eb-9760-054a9470ca63.png)
- In Chrome or Edge
![image](https://user-images.githubusercontent.com/3501554/115985204-5bf8b400-a5c8-11eb-8a7f-49a47838a237.png)

**Comment by tanishq-arya** [comment]
Please assign me this issue.

**Comment by ishwari20** [comment]
@harikesh409 I would like to work on it. Please assign it to me.

**Comment by harikesh409** [comment]
Go ahead @ishwari20

**Comment by raks924** [comment]
hey @harikesh409 can i work on this issue?

**Comment by harikesh409** [comment]
> hey @harikesh409 can i work on this issue?

Already @ishwari20 has been assigned on this issue if she shows not progress in another 3 to 4 days then I will assign it to you.
