### ISSUE TITLE
Scroll bar not scrolling smoothly

### ISSUE THREAD

**Issue by RuchiGitHu** [Algo-Phantoms/Algo-Phantoms-Frontend#464]
## **Is your feature request related to a problem? Please describe.**

I want to make scroll bar run bottom to top with smoothness

## **Describe the solution you'd like**

I will reduce speed of scrolling with smoothness.

**Comment by harikesh409** [comment]
Already [scroll-behavior: smooth;](https://github.com/Algo-Phantoms/Algo-Phantoms-Frontend/blob/c15b95be78da55394191211befbfc7e3293a3640/css/style.css#L53-L54) is present in the CSS what else are you planning to add to make it more smoother?

**Comment by RuchiGitHu** [comment]
> Already [scroll-behavior: smooth;](https://github.com/Algo-Phantoms/Algo-Phantoms-Frontend/blob/c15b95be78da55394191211befbfc7e3293a3640/css/style.css#L53-L54) is present in the CSS what else are you planning to add to make it more smoother?

ok, I didn't knew about it, thanks for clearing....
