### ISSUE TITLE
FAQs Modification in Design

### ISSUE THREAD

**Issue by Anmolreshi** [Algo-Phantoms/Algo-Phantoms-Frontend#466]
I would like to redesign FAQ section of webapp and data would be random ! Just want to contribute to open source

**Comment by harikesh409** [comment]
What kind of design changes are you proposing? If possible show us some rough screnshots.

**Comment by Anmolreshi** [comment]
Okay I shall share with you screenshots of design

**Comment by Ankita297** [comment]
Can i work on this @harikesh409 @ravikr126 ?

**Comment by ravikr126** [comment]
> What kind of design changes are you proposing? If possible show us some rough screnshots.

@Ankita297

**Comment by Ankita297** [comment]
we can change the design of faq page by box shadow ,hover effect ,styling of it .

**Comment by Anmolreshi** [comment]
@ravikr126  I am working on this .

**Comment by ravikr126** [comment]
Ok @Anmolreshi

**Comment by Anmolreshi** [comment]
Thank You

**Comment by Anmolreshi** [comment]
@ravikr126  I have added a Pull request #509  Kindly review it .
