### ISSUE TITLE
We can add some team related image instead of this circle in the "Team" page.

### ISSUE THREAD

**Issue by aanchalrakheja** [Algo-Phantoms/Algo-Phantoms-Frontend#468]
![image](https://user-images.githubusercontent.com/68388581/117502758-98032000-af9d-11eb-9062-d3de9faa93a7.png)

**Comment by harikesh409** [comment]
Go ahead and add if you are unable to find any image then you can add the logo itesef.

**Comment by prayas7102** [comment]
@harikesh409 sir can i work on this project? I am also comfortable to collaborate with @aanchalrakheja .

**Comment by harikesh409** [comment]
> ![team logo](https://user-images.githubusercontent.com/68388581/117818016-ce82b880-b285-11eb-8efb-92e4241676ed.png)
> How is this picture?

The picture looks good but need to see if it goes with the website page or not.

**Comment by harikesh409** [comment]
> @harikesh409 sir can i work on this project? I am also comfortable to collaborate with @aanchalrakheja .

I don't think this issue is needed to be done by 2 members, look into some other issue.

**Comment by aanchalrakheja** [comment]
> > ![team logo](https://user-images.githubusercontent.com/68388581/117818016-ce82b880-b285-11eb-8efb-92e4241676ed.png)
> > How is this picture?
> 
> The picture looks good but need to see if it goes with the website page or not.

Will try placing it once and adjusting the color scheme.

**Comment by aanchalrakheja** [comment]
![image](https://user-images.githubusercontent.com/68388581/118311990-4ebb4f00-b50e-11eb-8ab4-aba34f14db8d.png)
This is how it looks. Should I continue with it?

**Comment by harikesh409** [comment]
Looks good go ahead.

**Comment by aanchalrakheja** [comment]
Ok sure
