### ISSUE TITLE
Create a Site Map for the Website

### ISSUE THREAD

**Issue by chaitanyashimpi** [Algo-Phantoms/Algo-Phantoms-Frontend#47]
@anubhavitis 
It is necessary that your website should have the **siteMap**. 

I would like to solve this issue, can you please assign it to me.

**Comment by chaitanyashimpi** [comment]
I would like if you assign the issue to me. @tarun26091999

**Comment by chaitanyashimpi** [comment]
I would like to solve this issue as the part of GSSOC. @todi-2000

**Comment by Shruti3004** [comment]
@chaitanyashimpi go ahead
