### ISSUE TITLE
Enhance responsiveness

### ISSUE THREAD

**Issue by Saumya-07** [Algo-Phantoms/Algo-Phantoms-Frontend#470]
## **Describe the bug**
Make a better responsive webpage

## **Possible solution**
I would like to make responsive this sharpen skill section

## **Screenshots**
![Screenshot (571)](https://user-images.githubusercontent.com/68998355/117581151-015b6e00-b119-11eb-8f8d-9201e60a9384.png)

I am a GSSOC'21 participant and would like to work on this issue.
please assign this issue to me if you find it valid.

**Comment by arpit456jain** [comment]
I am also interested in this issue . I can solve it within 3 hours.

**Comment by harikesh409** [comment]
As @Saumya-07 asked first I am assigning it to her and give her time if she wasn't able to complete it I will assign it to you @arpit456jain

**Comment by Saumya-07** [comment]
Please review PR #496 @harikesh409
