### ISSUE TITLE
Adding animations in home page

### ISSUE THREAD

**Issue by PranavChauhan22** [Algo-Phantoms/Algo-Phantoms-Frontend#471]
I want to add animations in home page so that it doesn't appear to be static to customers plus i also want to include transition 
effect in email section of footer.

**Comment by PranavChauhan22** [comment]
should i proceed on this task mentors/admins ?

**Comment by harikesh409** [comment]
Email transition is not needed and what kind of animations are you talking about?

**Comment by PranavChauhan22** [comment]
I want to add scroll animations in about page and i also want to add a background animations like rotating globe in about page.
You can go through the landing page of my blog for better description of the same.
https://pranavchauhan22.github.io/PranavBlog/pranavblog.html

**Comment by PranavChauhan22** [comment]
should i proceed for it..?

**Comment by harikesh409** [comment]
Not needed.
