### ISSUE TITLE
Replacing the existing scrollbar

### ISSUE THREAD

**Issue by siddharth-bhatnagar** [Algo-Phantoms/Algo-Phantoms-Frontend#474]
## **Is your feature request related to a problem? Please describe.**
I am a GSSOC'21 participant, and I would like to make changes to the existing scrollbar.

## **Describe the solution you'd like**
Replacing the existing scrollbar with a variation of Perfect Scrollbar (npm) would make the overall website look much cleaner.

**Comment by harikesh409** [comment]
Not needed.
