### ISSUE TITLE
Sharpen your skill enhancement

### ISSUE THREAD

**Issue by Ankita297** [Algo-Phantoms/Algo-Phantoms-Frontend#476]
## Proposal
the  current section is not aligned properly  or we can convert it into cards  which will look better or we can align it center 

(A clear and concise description of what the proposal is.)
![Algo Phantoms - Google Chrome 12-05-2021 22_39_37](https://user-images.githubusercontent.com/67833077/118016833-7e821f80-b373-11eb-995e-c116e03cc244.png)

**Comment by Ankita297** [comment]
@ravikr126 can i work on this ?

**Comment by ravikr126** [comment]
May be someone already raised this issue .Please check once again the previous issue .If this issue not available then I will assign to you @Ankita297

**Comment by Ankita297** [comment]
@ravikr126  Sir there are issues related to it but it is not assigned to someone  and also i am thinking of converting these items into cards form which will look more interactive .

**Comment by harikesh409** [comment]
> @ravikr126 Sir there are issues related to it but it is not assigned to someone and also i am thinking of converting these items into cards form which will look more interactive .

Are you saying that you want to create a card for each skill and show it in a grid layout?

**Comment by Ankita297** [comment]
Yes @harikesh409 .

**Comment by harikesh409** [comment]
go ahead @Ankita297
