### ISSUE TITLE
Bug in home page

### ISSUE THREAD

**Issue by arpit456jain** [Algo-Phantoms/Algo-Phantoms-Frontend#480]
## **Describe the bug**

Due to table present there is a bug in home page its looking like this in mobile view
<img width="960" alt="bug in home" src="https://user-images.githubusercontent.com/55352601/118254398-ae8f0700-b4c8-11eb-96ae-0416f4c1895a.png">

## **Possible solution**

I have to remove extra space and decrease its font size so that it fits in small screem\n

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@harikesh409 can I start work please assign me this issue . I will make the PR as soon as possible

**Comment by harikesh409** [comment]
There are many similar responsiveness issues so I can't assign it to you.
#470
