### ISSUE TITLE
Add animation to the about us section

### ISSUE THREAD

**Issue by sohini3062** [Algo-Phantoms/Algo-Phantoms-Frontend#49]
I am a GSSOC '21 participant.

I wish to add a typing animation to the about us section using css and javascript

**Comment by ArchishmanSengupta** [comment]
Hey i am a GSSoc'21 participant i want to add a dispersion of text which when pointed by cursor will disperse using Javascript.

Please assign me the task! Thank you

**Comment by Priyanka7011** [comment]
Hii!
I am a GSSOC 2021 participant.
I would like to add animation on about us section . The heading would expand to 1.5x on hover and the text section would be in a transparent box which glows up on hovering .

**Comment by pi-squared-4** [comment]
Hi, I would love to work on this, can you please assign me. I would do better.

**Comment by Shruti3004** [comment]
@ArchishmanSengupta @Priyanka7011
