### ISSUE TITLE
sharpen your skills

### ISSUE THREAD

**Issue by ravikr126** [Algo-Phantoms/Algo-Phantoms-Frontend#490]
## **Describe the bug**

- in mobile view, sharpen your skill section is not show 

## **Possible solution**

- align at the 
![algo-phantoms github io_Algo-Phantoms-Frontend_index html (1)](https://user-images.githubusercontent.com/53082978/118387170-6db6ff80-b63a-11eb-90f4-387fbb5999e7.png)
center

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by ishwari20** [comment]
@ravikr126 I would like to work on this issue. Please assign it to me

**Comment by Muskan-creator** [comment]
@harikesh409 I want to work on this issue please assign it to me.

**Comment by ravikr126** [comment]
you can work now @ishwari20

**Comment by ishwari20** [comment]
@ravikr126 I run the code, so the "Sharpen your skills" section is visible in phone view also. Will you please check it once and let me know?

**Comment by ravikr126** [comment]
Yes @ishwari20 it look fine in chrome .I think mene kisi other browser me dekha tha ushme thoda error aaraha tha.so I will close this issue.
