### ISSUE TITLE
footer section

### ISSUE THREAD

**Issue by ravikr126** [Algo-Phantoms/Algo-Phantoms-Frontend#491]
## **Describe the bug**

- in mobile view , footer section is not aligned

## **Possible solution**

- align at the center
![algo-phantoms github io_Algo-Phantoms-Frontend_index html](https://user-images.githubusercontent.com/53082978/118387205-ae167d80-b63a-11eb-8622-3e8ef2891e2e.png)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by kanishka8276** [comment]
@ravikr126 Please assign this to me.
GSSoC'21
