### ISSUE TITLE
Setting up eslint and linting the code 

### ISSUE THREAD

**Issue by subhangi2731** [Algo-Phantoms/Algo-Phantoms-Frontend#497]
I want to make the code prettier by setting up eslint in the project and linting the code

**Comment by subhangi2731** [comment]
@ravikr126 please assign this issue to me

**Comment by harikesh409** [comment]
Go ahead @subhangi2731

**Comment by subhangi2731** [comment]
@harikesh409 thanku can u please provide the gssoc and level tags

**Comment by harikesh409** [comment]
Reopening as it is not resolved.

**Comment by harikesh409** [comment]
Moved to #518
