### ISSUE TITLE
Adding space in paragraph

### ISSUE THREAD

**Issue by NehaK745** [Algo-Phantoms/Algo-Phantoms-Frontend#500]
## **Describe the bug**

I think adding space in the paragraph after the text "Open source organization" will look better. 
please allow me to make a PR.

## **Screenshots**

- If applicable, a
![Algo Phantoms - Google Chrome 18-05-2021 5_43_22 (2)](https://user-images.githubusercontent.com/64440607/118574384-eedcd680-b7a1-11eb-907c-fe160fe640a2.png)
dd screenshots to help explain your problem.

**Comment by harikesh409** [comment]
Go ahead @NehaK745
