### ISSUE TITLE
Adding some source codes in Sharpen Your Skills section

### ISSUE THREAD

**Issue by Astrodevil** [Algo-Phantoms/Algo-Phantoms-Frontend#506]
I am GSSoC participant
## **Is your feature request related to a problem? Please describe.**

- I just want to add some source codes related to (Sharpen Your Skills) section of Algo Phantom website.

## **Describe the solution you'd like**

- I want to add some codes and resource from below repository to your website *Sharpen your Skill* Section.
## **Please visit this link to see what items i want to add**
- https://github.com/Astrodevil/Programming-Basics

**Comment by harikesh409** [comment]
Not needed.
