### ISSUE TITLE
Add contact us form in the contact section.

### ISSUE THREAD

**Issue by padmajabhol** [Algo-Phantoms/Algo-Phantoms-Frontend#51]
I want to make the contact us section better by adding a form. Please assign me this issue.

**Comment by Simran2337** [comment]
I want to contribute. Thankyou

**Comment by Divya871** [comment]
I want to contribute. Thank you!

**Comment by Riya764** [comment]
I would like to work on this issue.Please assign this to me as a part of GSSOC'21

**Comment by 435akashjha** [comment]
I want to contribute so that in contact section of the page a form can be made where the user can contact.Assign it to me.

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by harikesh409** [comment]
@padmajabhol and @shubhraagarwal can work together on this issue if there is no problem for you people.

**Comment by padmajabhol** [comment]
> @padmajabhol and @shubhraagarwal can work together on this issue if there is no problem for you people.

I d love to. There's no issue.

**Comment by shubhraagarwal** [comment]
Sure👌

**Comment by harikesh409** [comment]
@padmajabhol and @shubhraagarwal what is the progress of the form as it is already been a week?

**Comment by RahulBansal0502** [comment]
I want to work on this issue. Please assign it to me as a GSSOC participant.

**Comment by ravikr126** [comment]
@padmajabhol and @shubhraagarwal completed ????

**Comment by ravikr126** [comment]
> I want to work on this issue. Please assign it to me as a GSSOC participant.

if anyone not working on it then next participant will assign

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant. could you please assign me this?

**Comment by padmajabhol** [comment]
> @padmajabhol and @shubhraagarwal completed ????

I am working on it. Will send pr.

**Comment by padmajabhol** [comment]
> > I want to work on this issue. Please assign it to me as a GSSOC participant.
> 
> if anyone not working on it then next participant will assign 

I thought the other person was about to work on it too as you assigned both of us, sorry if there was any misunderstanding. I have sent the PR, do review it.

**Comment by harshb02** [comment]
![demo4](https://user-images.githubusercontent.com/58955446/113482657-4575a600-94bd-11eb-9306-d6f7307aec35.gif)

I will make the contact us form like this.
If you feel this is better then please assign this issue to me @harikesh409 @ravikr126

**Comment by harikesh409** [comment]
> ![demo4](https://user-images.githubusercontent.com/58955446/113482657-4575a600-94bd-11eb-9306-d6f7307aec35.gif)
> 
> I will make the contact us form like this.
> If you feel this is better then please assign this issue to me @harikesh409 @ravikr126

It is already been built in #300 and review is going on. Work on some other issue.

**Comment by harshb02** [comment]
But you had some issues regarding the design of the form. So Ravi Bhaiya said if you like the design of my form then you can assign this issue to me

**Comment by ravikr126** [comment]
@harshb02 if @padmajabhol not working on it then you will work.till now she work on it so we can't assign you

**Comment by harshb02** [comment]
Okay not a problem @ravikr126

**Comment by ravikr126** [comment]
hii @padmajabhol  .are you complete with your work???

**Comment by harshb02** [comment]
I want to work on this issue if not completed @ravikr126

**Comment by ravikr126** [comment]
@harshb02 you can work on it

**Comment by RahulBansal0502** [comment]
> I want to work on this issue. Please assign it to me as a GSSOC participant.

I was commented first @ravikr126

**Comment by ravikr126** [comment]
sorry @RahulBansal0502 i forget to see your comment .please you can choose different issue

**Comment by Abhishekkr93** [comment]
I want to fix this, please assign me

**Comment by AnjiAgrawal** [comment]
Can I work for this as a participant of GSSOC21.. I can solve it.

**Comment by harikesh409** [comment]
It is almost ready so look into other isssues. @Abhishekkr93 @AnjiAgrawal
