### ISSUE TITLE
About us Text

### ISSUE THREAD

**Issue by tanishq-arya** [Algo-Phantoms/Algo-Phantoms-Frontend#513]
## Proposal

Modify the about us text. Content as well as font-size. The text in paragraph now looks very odd. 

![image](https://user-images.githubusercontent.com/77333275/119269091-99764e80-bc13-11eb-89ae-a8e28f07934e.png)

**Comment by tanishq-arya** [comment]
Please assign me this issue.

**Comment by harikesh409** [comment]
No need to change it.
