### ISSUE TITLE
Suggested books navbar option is not present in dsa.html

### ISSUE THREAD

**Issue by kanishka8276** [Algo-Phantoms/Algo-Phantoms-Frontend#520]
## **Describe the bug**
The navbar of DSA.html does not have Suggested books link. 
## **Possible solution**
I will like to add the link.
## **Screenshots**
![Screenshot (29)](https://user-images.githubusercontent.com/66053534/120058644-02255700-c06a-11eb-83e4-c695ae8d4f15.png)

Please assign this to me.
GSSoC'21

**Comment by harikesh409** [comment]
Go ahead @kanishka8276
