### ISSUE TITLE
issue and pr templates

### ISSUE THREAD

**Issue by Sloth-Panda** [Algo-Phantoms/Algo-Phantoms-Frontend#53]
would like to add issue and pr templates

**Comment by Shruti3004** [comment]
go ahead @Sloth-Panda

**Comment by Sloth-Panda** [comment]
@Shruti3004 hey, plz add gssoc'21 and other required tags to this issue :p

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by harikesh409** [comment]
> hello
> i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

Assiging to @Sloth-Panda as it is First Come First Serve basis you can check other issues.

**Comment by Aryamanz29** [comment]
@Sloth-Panda  are you still working on this issue?

**Comment by Sloth-Panda** [comment]
@Aryamanz29 of course I am just got assigned yesterday

**Comment by Sloth-Panda** [comment]
@Shruti3004  @harikesh409 lol, I have already made or for this please check it's  been nearly a week now and it's a simple pr should not be taking much time

**Comment by harikesh409** [comment]
> @Shruti3004 @harikesh409 lol, I have already made pr for this please check it's been nearly a week now and it's a simple pr should not be taking much time, just scroll up I have mentioned the pr there

I have requested a change in the PR look into it and resolve it.
