### ISSUE TITLE
Github Bot Feature

### ISSUE THREAD

**Issue by Sukriti-sood** [Algo-Phantoms/Algo-Phantoms-Frontend#530]
Github Bot Will COmment on Every PR Open and PR merged

**Comment by harikesh409** [comment]
Already a bot is present to greet the users.

**Comment by Sukriti-sood** [comment]
> Already a bot is present to greet the users.

But that is only for first time contributors .

**Comment by harikesh409** [comment]
> > Already a bot is present to greet the users.
> 
> But that is only for first time contributors .

That is enough we don't want unnecessary bot comments on every PR.
