### ISSUE TITLE
Heading of "Sharpen Your Skills" is not in similarity with others

### ISSUE THREAD

**Issue by MonalikaKapoor** [Algo-Phantoms/Algo-Phantoms-Frontend#532]
## **Describe the bug**

The heading of "Sharpen Your Skills" is not looking in line with others, the font size is less and not bold enough in comparison to others.

## **Possible solution**

Match the css

## **Screenshots**
![image](https://user-images.githubusercontent.com/67543895/120112592-16657300-c194-11eb-8556-d8e563af634a.png)

- If applicable, add screenshots to help explain your problem.

**Comment by harikesh409** [comment]
Go ahead @MonalikaKapoor
