### ISSUE TITLE
Designed Contact Us section and made it responsive

### ISSUE THREAD

**Issue by ishitakapoor26** [Algo-Phantoms/Algo-Phantoms-Frontend#534]
Added map to contact us section and added user details section.

**Comment by ishitakapoor26** [comment]
Please assign me this issue.

**Comment by ishitakapoor26** [comment]
I've already completed it. Pls assign me.

**Comment by ishitakapoor26** [comment]
Please check I have created a pull request Designed Contact Us#534 #536
commit d7c7ba6

**Comment by harikesh409** [comment]
Not needed as already a contact page is present.
