### ISSUE TITLE
Updated FAQ section

### ISSUE THREAD

**Issue by ishitakapoor26** [Algo-Phantoms/Algo-Phantoms-Frontend#539]
![Capture3](https://user-images.githubusercontent.com/78542333/120118458-3dca3900-c1b0-11eb-9f79-d676e4b01716.PNG)
Fixed above by adding some questions and their answers accordingly.

**Comment by ishitakapoor26** [comment]
Pls assign me this issue @harikesh409 @anubhavitis @parthpandyappp @chaitanyashimpi

**Comment by ishitakapoor26** [comment]
pls review my pr #540 @harikesh409

**Comment by ishitakapoor26** [comment]
@harikesh409 pls review my pr.

**Comment by ishitakapoor26** [comment]
@harikesh409 removed contact us pls review and merge pr.

**Comment by harikesh409** [comment]
> @harikesh409 removed contact us pls review and merge pr.

resolve merge conflicts.
