### ISSUE TITLE
Add an animated search bar to the navigation bar

### ISSUE THREAD

**Issue by debjani1413** [Algo-Phantoms/Algo-Phantoms-Frontend#55]
Hello, I am a GSSOC'21 participant and I would like to add an animated search bar to the navigation bar.  I would be very  grateful if this issue is assigned to me.

**Comment by Simran2337** [comment]
i want to contribute as a GSSOC participant

**Comment by ravikr126** [comment]
you can start now @debjani1413

**Comment by debjani1413** [comment]
> you can start now @debjani1413

Okay, sir, I'll do the same!!

**Comment by ravikr126** [comment]
any progress @debjani1413 ???

**Comment by debjani1413** [comment]
Hello, @ravikr126, the work is done, just trying to figure out where to put the search-icon so that it looks appealing! I Will upload it 
in a day or two.

**Comment by debjani1413** [comment]
Hello, I've created a pull request for this issue, do check and let me know if there is anything else I need to change!

**Comment by harikesh409** [comment]
@debjani1413 
What is the functionality for the search bar?
