### ISSUE TITLE
Back to Top Button 

### ISSUE THREAD

**Issue by tanishq-arya** [Algo-Phantoms/Algo-Phantoms-Frontend#56]
The button is not visible due to it's dark color. I would like to suggest to add some contrast to it by changing some CSS on the button for it's color, preferably to white.
Please assign me this issue as a GSSOC participant. 
![Screenshot (937)](https://user-images.githubusercontent.com/77333275/110419845-19ceee00-80c0-11eb-8394-234e86ba4448.png)

**Comment by Simran2337** [comment]
i want to contribute as a GSSOC participant

**Comment by Riya764** [comment]
I would like to work on this issue.Please assign this to me as a part of GSSOC'21

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021.
Thank you

**Comment by lipsa199** [comment]
I am GSSOC participant , I would like to work on this issue.

**Comment by Mirnalin** [comment]
Hey! I am GSSOC participant , I would like to work on this issue.

**Comment by ravikr126** [comment]
> The button is not visible due to it's dark color. I would like to suggest to add some contrast to it by changing some CSS on the button for it's color, preferably to white.
> Please assign me this issue as a GSSOC participant.
> ![Screenshot (937)](https://user-images.githubusercontent.com/77333275/110419845-19ceee00-80c0-11eb-8394-234e86ba4448.png)

you can start now

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by tanishq-arya** [comment]
#131
