### ISSUE TITLE
Change Text Size to resolve overlapping

### ISSUE THREAD

**Issue by hgoyal254** [Algo-Phantoms/Algo-Phantoms-Frontend#60]
![image](https://user-images.githubusercontent.com/47057631/110431905-6a504680-80d4-11eb-8cf5-da0796236a55.png)

As we can see from the provided image that on resizing the window size the text is overlapping. I want to resolve this issue.

Please assign me this issue as a GSSOC Participant.

**Comment by Aditya7494** [comment]
I am a GSSOC'21 participant and i am interested to work on this issue.
Can you please assign it to me?

**Comment by rk05-lenavo** [comment]
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

**Comment by ravikr126** [comment]
someone did this issue.
