### ISSUE TITLE
Heading text not aligned properly

### ISSUE THREAD

**Issue by somya51p** [Algo-Phantoms/Algo-Phantoms-Frontend#62]
The title on the main page "We are Programmers, Algo Phantoms is an Open Source organization focusses on Data Structure and Algorithms" is not centered aligned. 

I wish to work on this issue under [GSSoC'21].

**Comment by Simran2337** [comment]
i want to contribute as a GSSOC participant

**Comment by ShrutiKhatri826** [comment]
I am a GSSOC'21 participant. I would love to take on this issue. Can you please assign it to me? Hope to hear from you soon!
