### ISSUE TITLE
the contact us button on hover should have some styling

### ISSUE THREAD

**Issue by gnikita432** [Algo-Phantoms/Algo-Phantoms-Frontend#63]
the contact us button should have a cursor: pointer and also have some background color or color changed when the user hovers on it.
![issue1](https://user-images.githubusercontent.com/61223163/110438214-2a8d5d00-80dc-11eb-935b-b00932f77458.PNG)
![issue2](https://user-images.githubusercontent.com/61223163/110438291-3711b580-80dc-11eb-8e7e-3d8550badde7.PNG)

**Comment by gnikita432** [comment]
I want to contribute to this as a GSSOC'21 participant. please assign it me.

**Comment by 435akashjha** [comment]
I can make the contact us hover with adding a background color or effect so that it looks nice.
Assign it to me.

**Comment by Shruti3004** [comment]
go ahead @gnikita432

**Comment by gnikita432** [comment]
Hey @Shruti3004, thank you for assigning the issue. Can you please label this issue with **gssoc'21** so that my contribution will get counted under gssoc.

**Comment by devanshi-code** [comment]
@gnikita432 Can I contribute to it

**Comment by rk05-lenavo** [comment]
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.
