### ISSUE TITLE
video playing in background is not smooth.

### ISSUE THREAD

**Issue by bug-debug-done** [Algo-Phantoms/Algo-Phantoms-Frontend#64]
Hey! I am a participant for GSSOC'21.
The video in the background is not smooth it gets stuck sometimes.  And it's also easy to tell when the video ended even though it is on autoplay loop. It does not look good
I can solve this please assign this issue to me.

**Comment by Shruti3004** [comment]
@bug-debug-done how you are planning to solve it, can you share a glipmse of it

**Comment by ravikr126** [comment]
you like to work on it or not @bug-debug-done ???
so tell me how you are planning to solve it, can you share a glimpse of it???

**Comment by bug-debug-done** [comment]
@Shruti3004 @ravikr126  sorry for the delay. I will reduce the video size and create another video which will be play backward .I will put both the video on loop one after another or can also combine the video and play that on loop.

**Comment by ravikr126** [comment]
can you show that video that you want to add? @bug-debug-done

**Comment by bug-debug-done** [comment]
ok I'll send the video

**Comment by bug-debug-done** [comment]
@ravikr126 hey I cannot add video whose size is more than 10 mb

**Comment by bug-debug-done** [comment]
I have combine the original video and the reverse video and made it one it will play on loop

**Comment by harikesh409** [comment]
@bug-debug-done 
In the live site we are not using `video.mp4` file it has been updated to `background.gif` in #120, this is done to improve the performance of the site and don't add an video which of huge size which will drastically drop the page load speed.

**Comment by bug-debug-done** [comment]
ok
