### ISSUE TITLE
improvement in footer section

### ISSUE THREAD

**Issue by bug-debug-done** [Algo-Phantoms/Algo-Phantoms-Frontend#65]
Hey! I am a participant for GSSOC'21
In the footer section after the contact us section, there should be the algo-phantoms icon and its description on its side.
And beneath that, there should be other options and links. and there can also be line beneath the column heading like useful links, features, and follow us.
I would like to work on this issue please assign this to me.

**Comment by WebVishal** [comment]
I want to contribute to this bug, Can I it?

**Comment by aanchalrakheja** [comment]
Hey!! I am a participant in GSSOC'21 and would like to contribute to this issue. Can u assign this to me please.

**Comment by Shruti3004** [comment]
@bug-debug-done yours

**Comment by Shruti3004** [comment]
@WebVishal @aanchalrakheja @kumarishalini6 issues are assigned on the first come first serve basis, you can look for the other issues and can open the issues of yours.

**Comment by ravikr126** [comment]
are you completed this isssue @bug-debug-done ???

**Comment by bug-debug-done** [comment]
@ravikr126  Yes, I have compleated  I'll  make a pull request tonight.

**Comment by Ankita297** [comment]
@ravikr126 can i work on this ?

**Comment by bug-debug-done** [comment]
Hey @ravikr126 please have a look at the pic do you want me to give even space between usefull links, features and follow us
![Screenshot from 2021-04-02 00-29-02](https://user-images.githubusercontent.com/75927761/113341510-dbd58a80-934a-11eb-9627-12ff9dad8fff.png)
