### ISSUE TITLE
Adding social media sidebar for the website.

### ISSUE THREAD

**Issue by Surabhi0910** [Algo-Phantoms/Algo-Phantoms-Frontend#68]
Hey! I am a participant for GSSOC'21. I would like to make this contribution to making a social media sidebar for the site with attractive icons which will hold the links to your social media handles. Please, consider! And assign it to me so that I can start working on it at the earliest.

**Comment by ambivert-sam** [comment]
Hey!!
@Shruti3004 I am participate at GSSoC'21 I would like to work with this issue
Would you please assign it to me?
I'll put my best in it.
