### ISSUE TITLE
re-sizing main-head and improvement in footer

### ISSUE THREAD

**Issue by pbpcodes** [Algo-Phantoms/Algo-Phantoms-Frontend#72]
Hello. I am a GSSoC'21 participant. I would like to resize the main-head which says 
 "We are Programmers 
Algo Phantoms is an Open Source organization focusses on Data Structure and Algorithms"

In desktop, the text is set to margin: 0 and hence, it is shifted to the right. Also, there is a typo in the word "focusses".

In the footer, the contact us button has to be responsive and functional.

I would like to contribute to the project. Please assign this to me.

**Comment by kumarishalini6** [comment]
Hii, i would like to work in re-sizing main-head " Algo Phantoms is an Open Source organization focusses on Data Structure and Algorithms" it should be more atteractive , font-family should be attractive,
and i also want to make logo attractive,
and in  contact us input should be more ,
footer and contact us has to be  different.
i am participant of GSSoC21. i want to contribute , can i.

**Comment by Shruti3004** [comment]
@pbpcodes go ahead
