### ISSUE TITLE
Typographical error on the website's landing page

### ISSUE THREAD

**Issue by shalmoly79** [Algo-Phantoms/Algo-Phantoms-Frontend#73]
Hello, I'm a GSSOC'21 participant. The first thing that catches the eye is the typo on the landing text on the website's homepage.
Please assign this task to me, I point out minute errors and details that would be very much beneficial collectively. Lookin forward to contributing more.

**Comment by Shruti3004** [comment]
@shalmoly79 can you please elaborate your issue, with some screenshots

**Comment by shalmoly79** [comment]
![image_2021-03-10_121903](https://user-images.githubusercontent.com/74116513/110588279-cda4ac00-819a-11eb-97a9-c3dc0349c7bb.png)
@Shruti3004 The spelling of "focusses" needs to be corrected.

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by ravikr126** [comment]
ok @shalmoly79 you can work and also check all the grammar mistakes in this website

**Comment by anju218** [comment]
Hello, I am a GSSOC'21 participant. The typos are still not resolved in the landing page. I also feel the color scheme of the text and the background should be contrast. Please assign this issue to me.

**Comment by ravikr126** [comment]
hii @shalmoly79  are you completed with your work?

**Comment by raks924** [comment]
Hey @ravikr126 i would like to submit the pr by today itself.Kindly let me work on this issue

**Comment by harikesh409** [comment]
GO ahead @raks924 you can work on it.
