### ISSUE TITLE
Website's "About us" section is not convincing enough.

### ISSUE THREAD

**Issue by shalmoly79** [Algo-Phantoms/Algo-Phantoms-Frontend#74]
Hello Algo-phantoms, I am a GSSOC'21 participant. The "About us" section of this website does not look convincing enough to increase the frequency of visitors and users. CSS grid/flexbox can be used along with JavaScript to improve the UI/UX. Brief information/specification/categorization on why(e.g. - programming languages present, total number of questions present etc.) and how to use(e.g.- a small pathway in a diagrammatic/animation form) Algo Phantoms would be more helpful and interactive.
If you find this issue helpful then please assign me this task. Thanking you in advance.
Looking forward to contribute to this project.

**Comment by Shruti3004** [comment]
go ahead @shalmoly79

**Comment by shalmoly79** [comment]
Thank you so much.

**Comment by ambivert-sam** [comment]
Hey!!
@Shruti3004  I am participate at GSSoC'21 I would like to work with this issue
Would you please assign it to me?

**Comment by shalmoly79** [comment]
@Shruti3004 I'm assigned by you for this issue. I am actively working on it and I will complete my task within 12th March, 2021 positively. Please don't assign my issue to anybody else. Thank you.

**Comment by aditisingh2412** [comment]
Hey, can I solve this issue??
