### ISSUE TITLE
Footer part in not looking great.

### ISSUE THREAD

**Issue by Manish-kasera** [Algo-Phantoms/Algo-Phantoms-Frontend#77]
It's not looking as a different part of the website..This part is mixes with Contact us and  Useful links...
I would like to fix this Issue.
![issue](https://user-images.githubusercontent.com/66238224/110578804-8fec5700-818b-11eb-8f0e-c1d3cc2d7abb.png)

**Comment by Priyanka7011** [comment]
hii I am a GSSOC 2021 participant
I would love to work on this feature
please assign me this.

Thank You

**Comment by rk05-lenavo** [comment]
I'm the Participant in GSSOC'21. Could you please assign me this .

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by ravikr126** [comment]
you can work on iot @Manish-kasera
