### ISSUE TITLE
Link is not Working

### ISSUE THREAD

**Issue by Manish-kasera** [Algo-Phantoms/Algo-Phantoms-Frontend#78]
Issue : Hovering over Contact Us Text ,their is nothing happens...
Solution: We should give a link (link Email id) when anyone hover over contact us...

https://user-images.githubusercontent.com/66238224/110579466-e3ab7000-818c-11eb-9669-644a2611f1c4.mp4

**Comment by Goheljay** [comment]
I want to work on this issue. I participate in gssoc 2021. can you assign me

**Comment by surbhi594** [comment]
The Git hub link and all other social media links at the left side of Algo Phatoms website are not working. Please assign this issue to me as I'm the participant of GSSOC'21.

**Comment by harikesh409** [comment]
> The Git hub link and all other social media links at the left side of Algo Phatoms website are not working. Please assign this issue to me as I'm the participant of GSSOC'21.

create a new issue and ask there @surbhi594

**Comment by harikesh409** [comment]
> Issue : Hovering over Contact Us Text ,their is nothing happens...
> Solution: We should give a link (link Email id) when anyone hover over contact us...
> 
>  issue.mp4

The Contact Us over there is a heading and link is not needed over there.
