### ISSUE TITLE
Adding sliding images on home page

### ISSUE THREAD

**Issue by poojitha2002** [Algo-Phantoms/Algo-Phantoms-Frontend#79]
Could you please assign this issue to me? I would like to work on it.

**Comment by abhishek96k** [comment]
Please assign me this issue as a part of GSSoC'21

**Comment by ShrutiKhatri826** [comment]
I am a GSSOC'21 participant. I would love to take on this issue. Can you please assign it to me? Hope to hear from you soon!

**Comment by poojitha2002** [comment]
Hello,can you please assign this issue to me

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by ravikr126** [comment]
what sliding image you add @poojitha2002 ???

**Comment by Sejal260** [comment]
I  would like to work on it. Please provide me this issue so that I can start working on it.
