### ISSUE TITLE
Adding smooth scrolling in the back to top button

### ISSUE THREAD

**Issue by shubhraagarwal** [Algo-Phantoms/Algo-Phantoms-Frontend#81]
The scroll behaviour is not smooth in the back to top button, I would like to improve this as a part of GS'SOC21. Adding smooth scroll behaviour will make the UX better.

**Comment by Shruti3004** [comment]
go ahead @shubhraagarwal

**Comment by shubhraagarwal** [comment]
I have made a PR #96 with respect to this issue

**Comment by ishwari20** [comment]
@ravikr126 I want to work on this issue. Please assign it to me

**Comment by harshb02** [comment]
I want to work on this issue @ravikr126 @harikesh409

**Comment by harikesh409** [comment]
The issue is already resolved in #131
