### ISSUE TITLE
contributing file

### ISSUE THREAD

**Issue by Sloth-Panda** [Algo-Phantoms/Algo-Phantoms-Frontend#86]
There is no contributing.md file explaining how to  contribute to this repo so would like to add one

**Comment by Sloth-Panda** [comment]
@Shruti3004

**Comment by khareyash05** [comment]
Hi! I would like to work on this issue as a part of GSSOc'21

**Comment by ravikr126** [comment]
can you elaborate this file issue ??? @Sloth-Panda
