### ISSUE TITLE
Team members card correction.

### ISSUE THREAD

**Issue by 123mansha** [Algo-Phantoms/Algo-Phantoms-Frontend#88]
Hi !! I am a GSSOC'21 participant. The very first thing I saw is an error in the arrangement of the team member cards. So I want to want to improve the arrangements of the team member cards so that they will be aligned taking equal spaces and will look good. 
@Shruti3004 please assign this issue to me so that I can start working on it. 

![team](https://user-images.githubusercontent.com/59260493/110595278-d6e64680-81a3-11eb-9275-4b02e71f63d0.jpg)

**Comment by Shruti3004** [comment]
go ahead @123mansha

**Comment by 123mansha** [comment]
@Shruti3004 Please check the changes made #97

**Comment by ravikr126** [comment]
completed work??? @123mansha
