### ISSUE TITLE
Adding email validation and a functioning contact us button in contact section

### ISSUE THREAD

**Issue by aakankshabhende** [Algo-Phantoms/Algo-Phantoms-Frontend#89]
![image](https://user-images.githubusercontent.com/63249668/110608332-27fd3700-81b2-11eb-82e9-e7ac5a7bef5e.png)

**Comment by Aakanksha0407** [comment]
I am GSSOC'21 participant. 
I want to work on this issue. Can you please assign me this.

**Comment by Aditya201551** [comment]
This website does not use and backend stack so integrating email validation won't be possible but if you have any idea it would be great to work on this issue together!

ThankYou!(GSSOC participant)

**Comment by Aakanksha0407** [comment]
So sir can I add a floating button that will be linked directly to the GitHub profile. So it will be handy for the users and the same time will help in beautification.
Also I want to align this marked paragraph. This needs to be in centre.

![image](https://user-images.githubusercontent.com/63249668/110751064-5c7ffa00-8269-11eb-8ffa-438707f12e7d.png)

**Comment by Aditya201551** [comment]
yeah, you can do with the aligning thing but how would adding a Github link will help in email authentication?

and btw I am also a gssoc participant m not "sir"😅

anyways hope it helps

**Comment by ravikr126** [comment]
you can work on it @aakankshabhende
