### ISSUE TITLE
[GSSoC '21] Data structures simulation feature

### ISSUE THREAD

**Issue by amrzaki2000** [Algo-Phantoms/Algo-Phantoms-Frontend#90]
Hello,
I'm a GSSoC participant.
Can I work on a feature that provides simulation for operations in data structures ?
Eg. Simulation that shows how push and pop in stack works.

**Comment by amrzaki2000** [comment]
@todi-2000 @diyajaiswal11 

Can you assign this issues to me, please?
I would like to work on a data structures simulation section.

**Comment by amrzaki2000** [comment]
@todi-2000 @diyajaiswal11

**Comment by amrzaki2000** [comment]
@ravikr126 
Can you assign me this issue, please ?

**Comment by osamamagdy** [comment]
@todi-2000 @ravikr126 @diyajaiswal11   
I also want to be assigned to this issue with @amrzaki2000 if applicable.

**Comment by ravikr126** [comment]
you both can work now @osamamagdy @amrzaki2000

**Comment by ravikr126** [comment]
what is your progress @osamamagdy @amrzaki2000 ???

**Comment by ravikr126** [comment]
what is your progress @osamamagdy @amrzaki2000 ???

**Comment by ishwari20** [comment]
@ravikr126 I want to work on this issue. Please assign it to me

**Comment by ravikr126** [comment]
Ok @ishwari20 you can work on this issue

**Comment by ravikr126** [comment]
Yes @AnushkaS09 if @ishwari20 like to work with you then you will collaborate with @ishwari20

**Comment by AnushkaS09** [comment]
Yes @ishwari20  and I will be working together..Kindly assign me the issue @ravikr126
