### ISSUE TITLE
Spelling Mistakes in the footer.

### ISSUE THREAD

**Issue by FireQueen-3010** [Algo-Phantoms/Algo-Phantoms-Frontend#94]
"An Open Source organization focuses (should be focusing not focuses) on Data Structure and Algorithms." Under the logo in the footer section.
Please assign me this.

**Comment by HarinandhanPSGiTech** [comment]
Hi! I am a GSSOC'21 participant, I think the error on the footer is that the text describing the organization  should be "An Open Source organization  _**that**_  focuses  on Data Structure and Algorithms." 

I would love to contribute to this issue, Please assign this to me!

**Comment by FireQueen-3010** [comment]
Both "that focuses" and "focusing" mean the same. Since I raised this issue, please assign me this. Will go for the word which the admin assigns me as part of the GSSOC'21. Thank you!

**Comment by harikesh409** [comment]
The spellings are correct only no need to change those.
