### ISSUE TITLE
long footer section in Mobile Format 

### ISSUE THREAD

**Issue by WebVishal** [Algo-Phantoms/Algo-Phantoms-Frontend#95]
Hi !! I am a GSSOC'21 participant. I think some improvement in the Footer section. When I looked at the footer section on mobile, it is looking quite long, So I  want to improve the footer section by using flexbox and grid display property so that they will be aligned taking equal spaces and width and height, and will look good.
@Shruti3004 please assign this issue to me so that I can start working on it.

**Comment by harikesh409** [comment]
Go ahead @WebVishal

**Comment by ravikr126** [comment]
any progress @WebVishal ???

**Comment by harshb02** [comment]
Can I work on this issue?

**Comment by harikesh409** [comment]
are you still working on it @WebVishal? or else we will assign it to @harshb02

**Comment by WebVishal** [comment]
Hey @harikesh409  I have already give a pr #67 please Review the code
