### ISSUE TITLE
[GSSoC '21] Card hover effect

### ISSUE THREAD

**Issue by amrzaki2000** [Algo-Phantoms/Algo-Phantoms-Frontend#99]
Hello,
I noticed that this last card does not rotate on hover as other cards do.
I'd like to fix this as part of my GSSoC participation.
Thank you
![image](https://user-images.githubusercontent.com/62449903/110670802-758b9b00-81d6-11eb-96a1-720d2b44b209.png)

**Comment by shreya-1398** [comment]
> Hello,
> I noticed that this last card does not rotate on hover as other cards do.
> I'd like to fix this as part of my GSSoC participation.
> Thank you
> ![image](https://user-images.githubusercontent.com/62449903/110670802-758b9b00-81d6-11eb-96a1-720d2b44b209.png)

 You might be mistaken. It's working. Do check it, again

**Comment by shreya-1398** [comment]
@amrzaki2000  You might be mistaken. It's working.

**Comment by amrzaki2000** [comment]
@shreya-1398 looks like there was a problem with my browser
thanks
